//
// Generated automatically by generate_swizzle.py
//

// SWIZZLE MACRO BLOCK

use crate::vector::Vector;
use crate::real::*;

macro_rules! vector_swizzle_single {
    ($count:literal, $index:literal, $c:ident) => {
        impl<T: RealNumber> Vector<T, $count> {
            #[doc(hidden)]
            pub fn $c(&self) -> T {
                return self[$index];
            }
        }
    };
}

macro_rules! vector_swizzle_double {
    ($count:literal, $index:literal, $index2:literal, $cc:ident) => {
        impl<T: RealNumber> Vector<T, $count> {
            #[doc(hidden)]
            pub fn $cc(&self) -> Vector<T, 2> {
                return Vector::<T, 2>::new(self[$index], self[$index2]);
            }
        }
    };
}

macro_rules! vector_swizzle_triple {
    ($count:literal, $index:literal, $index2:literal, $index3:literal, $ccc:ident) => {
        impl<T: RealNumber> Vector<T, $count> {
            #[doc(hidden)]
            pub fn $ccc(&self) -> Vector<T, 3> {
                return Vector::<T, 3>::new(self[$index], self[$index2], self[$index3]);
            }
        }
    };
}

macro_rules! vector_swizzle_quadruple {
    ($count:literal, $index:literal, $index2:literal, $index3:literal, $index4:literal, $cccc:ident) => {
        impl<T: RealNumber> Vector<T, $count> {
            #[doc(hidden)]
            pub fn $cccc(&self) -> Vector<T, 4> {
                return Vector::<T, 4>::new(self[$index], self[$index2], self[$index3], self[$index4]);
            }
        }
    };
}

// -------------------

// VECTOR2 SWIZZLE BLOCK
vector_swizzle_single!(2, 0, x);
vector_swizzle_single!(2, 0, u);
vector_swizzle_single!(2, 0, s);
vector_swizzle_single!(2, 0, r);
vector_swizzle_single!(2, 1, y);
vector_swizzle_single!(2, 1, v);
vector_swizzle_single!(2, 1, t);
vector_swizzle_single!(2, 1, g);
vector_swizzle_double!(2, 0, 0, xx);
vector_swizzle_double!(2, 0, 0, uu);
vector_swizzle_double!(2, 0, 0, ss);
vector_swizzle_double!(2, 0, 0, rr);
vector_swizzle_double!(2, 0, 1, xy);
vector_swizzle_double!(2, 0, 1, uv);
vector_swizzle_double!(2, 0, 1, st);
vector_swizzle_double!(2, 0, 1, rg);
vector_swizzle_double!(2, 1, 0, yx);
vector_swizzle_double!(2, 1, 0, vu);
vector_swizzle_double!(2, 1, 0, ts);
vector_swizzle_double!(2, 1, 0, gr);
vector_swizzle_double!(2, 1, 1, yy);
vector_swizzle_double!(2, 1, 1, vv);
vector_swizzle_double!(2, 1, 1, tt);
vector_swizzle_double!(2, 1, 1, gg);
vector_swizzle_triple!(2, 0, 0, 0, xxx);
vector_swizzle_triple!(2, 0, 0, 0, uuu);
vector_swizzle_triple!(2, 0, 0, 0, sss);
vector_swizzle_triple!(2, 0, 0, 0, rrr);
vector_swizzle_triple!(2, 0, 0, 1, xxy);
vector_swizzle_triple!(2, 0, 0, 1, uuv);
vector_swizzle_triple!(2, 0, 0, 1, sst);
vector_swizzle_triple!(2, 0, 0, 1, rrg);
vector_swizzle_triple!(2, 0, 1, 0, xyx);
vector_swizzle_triple!(2, 0, 1, 0, uvu);
vector_swizzle_triple!(2, 0, 1, 0, sts);
vector_swizzle_triple!(2, 0, 1, 0, rgr);
vector_swizzle_triple!(2, 0, 1, 1, xyy);
vector_swizzle_triple!(2, 0, 1, 1, uvv);
vector_swizzle_triple!(2, 0, 1, 1, stt);
vector_swizzle_triple!(2, 0, 1, 1, rgg);
vector_swizzle_triple!(2, 1, 0, 0, yxx);
vector_swizzle_triple!(2, 1, 0, 0, vuu);
vector_swizzle_triple!(2, 1, 0, 0, tss);
vector_swizzle_triple!(2, 1, 0, 0, grr);
vector_swizzle_triple!(2, 1, 0, 1, yxy);
vector_swizzle_triple!(2, 1, 0, 1, vuv);
vector_swizzle_triple!(2, 1, 0, 1, tst);
vector_swizzle_triple!(2, 1, 0, 1, grg);
vector_swizzle_triple!(2, 1, 1, 0, yyx);
vector_swizzle_triple!(2, 1, 1, 0, vvu);
vector_swizzle_triple!(2, 1, 1, 0, tts);
vector_swizzle_triple!(2, 1, 1, 0, ggr);
vector_swizzle_triple!(2, 1, 1, 1, yyy);
vector_swizzle_triple!(2, 1, 1, 1, vvv);
vector_swizzle_triple!(2, 1, 1, 1, ttt);
vector_swizzle_triple!(2, 1, 1, 1, ggg);
vector_swizzle_quadruple!(2, 0, 0, 0, 0, xxxx);
vector_swizzle_quadruple!(2, 0, 0, 0, 0, uuuu);
vector_swizzle_quadruple!(2, 0, 0, 0, 0, ssss);
vector_swizzle_quadruple!(2, 0, 0, 0, 0, rrrr);
vector_swizzle_quadruple!(2, 0, 0, 0, 1, xxxy);
vector_swizzle_quadruple!(2, 0, 0, 0, 1, uuuv);
vector_swizzle_quadruple!(2, 0, 0, 0, 1, ssst);
vector_swizzle_quadruple!(2, 0, 0, 0, 1, rrrg);
vector_swizzle_quadruple!(2, 0, 0, 1, 0, xxyx);
vector_swizzle_quadruple!(2, 0, 0, 1, 0, uuvu);
vector_swizzle_quadruple!(2, 0, 0, 1, 0, ssts);
vector_swizzle_quadruple!(2, 0, 0, 1, 0, rrgr);
vector_swizzle_quadruple!(2, 0, 0, 1, 1, xxyy);
vector_swizzle_quadruple!(2, 0, 0, 1, 1, uuvv);
vector_swizzle_quadruple!(2, 0, 0, 1, 1, sstt);
vector_swizzle_quadruple!(2, 0, 0, 1, 1, rrgg);
vector_swizzle_quadruple!(2, 0, 1, 0, 0, xyxx);
vector_swizzle_quadruple!(2, 0, 1, 0, 0, uvuu);
vector_swizzle_quadruple!(2, 0, 1, 0, 0, stss);
vector_swizzle_quadruple!(2, 0, 1, 0, 0, rgrr);
vector_swizzle_quadruple!(2, 0, 1, 0, 1, xyxy);
vector_swizzle_quadruple!(2, 0, 1, 0, 1, uvuv);
vector_swizzle_quadruple!(2, 0, 1, 0, 1, stst);
vector_swizzle_quadruple!(2, 0, 1, 0, 1, rgrg);
vector_swizzle_quadruple!(2, 0, 1, 1, 0, xyyx);
vector_swizzle_quadruple!(2, 0, 1, 1, 0, uvvu);
vector_swizzle_quadruple!(2, 0, 1, 1, 0, stts);
vector_swizzle_quadruple!(2, 0, 1, 1, 0, rggr);
vector_swizzle_quadruple!(2, 0, 1, 1, 1, xyyy);
vector_swizzle_quadruple!(2, 0, 1, 1, 1, uvvv);
vector_swizzle_quadruple!(2, 0, 1, 1, 1, sttt);
vector_swizzle_quadruple!(2, 0, 1, 1, 1, rggg);
vector_swizzle_quadruple!(2, 1, 0, 0, 0, yxxx);
vector_swizzle_quadruple!(2, 1, 0, 0, 0, vuuu);
vector_swizzle_quadruple!(2, 1, 0, 0, 0, tsss);
vector_swizzle_quadruple!(2, 1, 0, 0, 0, grrr);
vector_swizzle_quadruple!(2, 1, 0, 0, 1, yxxy);
vector_swizzle_quadruple!(2, 1, 0, 0, 1, vuuv);
vector_swizzle_quadruple!(2, 1, 0, 0, 1, tsst);
vector_swizzle_quadruple!(2, 1, 0, 0, 1, grrg);
vector_swizzle_quadruple!(2, 1, 0, 1, 0, yxyx);
vector_swizzle_quadruple!(2, 1, 0, 1, 0, vuvu);
vector_swizzle_quadruple!(2, 1, 0, 1, 0, tsts);
vector_swizzle_quadruple!(2, 1, 0, 1, 0, grgr);
vector_swizzle_quadruple!(2, 1, 0, 1, 1, yxyy);
vector_swizzle_quadruple!(2, 1, 0, 1, 1, vuvv);
vector_swizzle_quadruple!(2, 1, 0, 1, 1, tstt);
vector_swizzle_quadruple!(2, 1, 0, 1, 1, grgg);
vector_swizzle_quadruple!(2, 1, 1, 0, 0, yyxx);
vector_swizzle_quadruple!(2, 1, 1, 0, 0, vvuu);
vector_swizzle_quadruple!(2, 1, 1, 0, 0, ttss);
vector_swizzle_quadruple!(2, 1, 1, 0, 0, ggrr);
vector_swizzle_quadruple!(2, 1, 1, 0, 1, yyxy);
vector_swizzle_quadruple!(2, 1, 1, 0, 1, vvuv);
vector_swizzle_quadruple!(2, 1, 1, 0, 1, ttst);
vector_swizzle_quadruple!(2, 1, 1, 0, 1, ggrg);
vector_swizzle_quadruple!(2, 1, 1, 1, 0, yyyx);
vector_swizzle_quadruple!(2, 1, 1, 1, 0, vvvu);
vector_swizzle_quadruple!(2, 1, 1, 1, 0, ttts);
vector_swizzle_quadruple!(2, 1, 1, 1, 0, gggr);
vector_swizzle_quadruple!(2, 1, 1, 1, 1, yyyy);
vector_swizzle_quadruple!(2, 1, 1, 1, 1, vvvv);
vector_swizzle_quadruple!(2, 1, 1, 1, 1, tttt);
vector_swizzle_quadruple!(2, 1, 1, 1, 1, gggg);
// ---------------------

// VECTOR3 SWIZZLE BLOCK
vector_swizzle_single!(3, 0, x);
vector_swizzle_single!(3, 0, u);
vector_swizzle_single!(3, 0, s);
vector_swizzle_single!(3, 0, r);
vector_swizzle_single!(3, 1, y);
vector_swizzle_single!(3, 1, v);
vector_swizzle_single!(3, 1, t);
vector_swizzle_single!(3, 1, g);
vector_swizzle_single!(3, 2, z);
vector_swizzle_single!(3, 2, q);
vector_swizzle_single!(3, 2, b);
vector_swizzle_double!(3, 0, 0, xx);
vector_swizzle_double!(3, 0, 0, uu);
vector_swizzle_double!(3, 0, 0, ss);
vector_swizzle_double!(3, 0, 0, rr);
vector_swizzle_double!(3, 0, 1, xy);
vector_swizzle_double!(3, 0, 1, uv);
vector_swizzle_double!(3, 0, 1, st);
vector_swizzle_double!(3, 0, 1, rg);
vector_swizzle_double!(3, 0, 2, xz);
vector_swizzle_double!(3, 0, 2, sq);
vector_swizzle_double!(3, 0, 2, rb);
vector_swizzle_double!(3, 1, 0, yx);
vector_swizzle_double!(3, 1, 0, vu);
vector_swizzle_double!(3, 1, 0, ts);
vector_swizzle_double!(3, 1, 0, gr);
vector_swizzle_double!(3, 1, 1, yy);
vector_swizzle_double!(3, 1, 1, vv);
vector_swizzle_double!(3, 1, 1, tt);
vector_swizzle_double!(3, 1, 1, gg);
vector_swizzle_double!(3, 1, 2, yz);
vector_swizzle_double!(3, 1, 2, tq);
vector_swizzle_double!(3, 1, 2, gb);
vector_swizzle_double!(3, 2, 0, zx);
vector_swizzle_double!(3, 2, 0, qs);
vector_swizzle_double!(3, 2, 0, br);
vector_swizzle_double!(3, 2, 1, zy);
vector_swizzle_double!(3, 2, 1, qt);
vector_swizzle_double!(3, 2, 1, bg);
vector_swizzle_double!(3, 2, 2, zz);
vector_swizzle_double!(3, 2, 2, qq);
vector_swizzle_double!(3, 2, 2, bb);
vector_swizzle_triple!(3, 0, 0, 0, xxx);
vector_swizzle_triple!(3, 0, 0, 0, uuu);
vector_swizzle_triple!(3, 0, 0, 0, sss);
vector_swizzle_triple!(3, 0, 0, 0, rrr);
vector_swizzle_triple!(3, 0, 0, 1, xxy);
vector_swizzle_triple!(3, 0, 0, 1, uuv);
vector_swizzle_triple!(3, 0, 0, 1, sst);
vector_swizzle_triple!(3, 0, 0, 1, rrg);
vector_swizzle_triple!(3, 0, 0, 2, xxz);
vector_swizzle_triple!(3, 0, 0, 2, ssq);
vector_swizzle_triple!(3, 0, 0, 2, rrb);
vector_swizzle_triple!(3, 0, 1, 0, xyx);
vector_swizzle_triple!(3, 0, 1, 0, uvu);
vector_swizzle_triple!(3, 0, 1, 0, sts);
vector_swizzle_triple!(3, 0, 1, 0, rgr);
vector_swizzle_triple!(3, 0, 1, 1, xyy);
vector_swizzle_triple!(3, 0, 1, 1, uvv);
vector_swizzle_triple!(3, 0, 1, 1, stt);
vector_swizzle_triple!(3, 0, 1, 1, rgg);
vector_swizzle_triple!(3, 0, 1, 2, xyz);
vector_swizzle_triple!(3, 0, 1, 2, stq);
vector_swizzle_triple!(3, 0, 1, 2, rgb);
vector_swizzle_triple!(3, 0, 2, 0, xzx);
vector_swizzle_triple!(3, 0, 2, 0, sqs);
vector_swizzle_triple!(3, 0, 2, 0, rbr);
vector_swizzle_triple!(3, 0, 2, 1, xzy);
vector_swizzle_triple!(3, 0, 2, 1, sqt);
vector_swizzle_triple!(3, 0, 2, 1, rbg);
vector_swizzle_triple!(3, 0, 2, 2, xzz);
vector_swizzle_triple!(3, 0, 2, 2, sqq);
vector_swizzle_triple!(3, 0, 2, 2, rbb);
vector_swizzle_triple!(3, 1, 0, 0, yxx);
vector_swizzle_triple!(3, 1, 0, 0, vuu);
vector_swizzle_triple!(3, 1, 0, 0, tss);
vector_swizzle_triple!(3, 1, 0, 0, grr);
vector_swizzle_triple!(3, 1, 0, 1, yxy);
vector_swizzle_triple!(3, 1, 0, 1, vuv);
vector_swizzle_triple!(3, 1, 0, 1, tst);
vector_swizzle_triple!(3, 1, 0, 1, grg);
vector_swizzle_triple!(3, 1, 0, 2, yxz);
vector_swizzle_triple!(3, 1, 0, 2, tsq);
vector_swizzle_triple!(3, 1, 0, 2, grb);
vector_swizzle_triple!(3, 1, 1, 0, yyx);
vector_swizzle_triple!(3, 1, 1, 0, vvu);
vector_swizzle_triple!(3, 1, 1, 0, tts);
vector_swizzle_triple!(3, 1, 1, 0, ggr);
vector_swizzle_triple!(3, 1, 1, 1, yyy);
vector_swizzle_triple!(3, 1, 1, 1, vvv);
vector_swizzle_triple!(3, 1, 1, 1, ttt);
vector_swizzle_triple!(3, 1, 1, 1, ggg);
vector_swizzle_triple!(3, 1, 1, 2, yyz);
vector_swizzle_triple!(3, 1, 1, 2, ttq);
vector_swizzle_triple!(3, 1, 1, 2, ggb);
vector_swizzle_triple!(3, 1, 2, 0, yzx);
vector_swizzle_triple!(3, 1, 2, 0, tqs);
vector_swizzle_triple!(3, 1, 2, 0, gbr);
vector_swizzle_triple!(3, 1, 2, 1, yzy);
vector_swizzle_triple!(3, 1, 2, 1, tqt);
vector_swizzle_triple!(3, 1, 2, 1, gbg);
vector_swizzle_triple!(3, 1, 2, 2, yzz);
vector_swizzle_triple!(3, 1, 2, 2, tqq);
vector_swizzle_triple!(3, 1, 2, 2, gbb);
vector_swizzle_triple!(3, 2, 0, 0, zxx);
vector_swizzle_triple!(3, 2, 0, 0, qss);
vector_swizzle_triple!(3, 2, 0, 0, brr);
vector_swizzle_triple!(3, 2, 0, 1, zxy);
vector_swizzle_triple!(3, 2, 0, 1, qst);
vector_swizzle_triple!(3, 2, 0, 1, brg);
vector_swizzle_triple!(3, 2, 0, 2, zxz);
vector_swizzle_triple!(3, 2, 0, 2, qsq);
vector_swizzle_triple!(3, 2, 0, 2, brb);
vector_swizzle_triple!(3, 2, 1, 0, zyx);
vector_swizzle_triple!(3, 2, 1, 0, qts);
vector_swizzle_triple!(3, 2, 1, 0, bgr);
vector_swizzle_triple!(3, 2, 1, 1, zyy);
vector_swizzle_triple!(3, 2, 1, 1, qtt);
vector_swizzle_triple!(3, 2, 1, 1, bgg);
vector_swizzle_triple!(3, 2, 1, 2, zyz);
vector_swizzle_triple!(3, 2, 1, 2, qtq);
vector_swizzle_triple!(3, 2, 1, 2, bgb);
vector_swizzle_triple!(3, 2, 2, 0, zzx);
vector_swizzle_triple!(3, 2, 2, 0, qqs);
vector_swizzle_triple!(3, 2, 2, 0, bbr);
vector_swizzle_triple!(3, 2, 2, 1, zzy);
vector_swizzle_triple!(3, 2, 2, 1, qqt);
vector_swizzle_triple!(3, 2, 2, 1, bbg);
vector_swizzle_triple!(3, 2, 2, 2, zzz);
vector_swizzle_triple!(3, 2, 2, 2, qqq);
vector_swizzle_triple!(3, 2, 2, 2, bbb);
vector_swizzle_quadruple!(3, 0, 0, 0, 0, xxxx);
vector_swizzle_quadruple!(3, 0, 0, 0, 0, uuuu);
vector_swizzle_quadruple!(3, 0, 0, 0, 0, ssss);
vector_swizzle_quadruple!(3, 0, 0, 0, 0, rrrr);
vector_swizzle_quadruple!(3, 0, 0, 0, 1, xxxy);
vector_swizzle_quadruple!(3, 0, 0, 0, 1, uuuv);
vector_swizzle_quadruple!(3, 0, 0, 0, 1, ssst);
vector_swizzle_quadruple!(3, 0, 0, 0, 1, rrrg);
vector_swizzle_quadruple!(3, 0, 0, 0, 2, xxxz);
vector_swizzle_quadruple!(3, 0, 0, 0, 2, sssq);
vector_swizzle_quadruple!(3, 0, 0, 0, 2, rrrb);
vector_swizzle_quadruple!(3, 0, 0, 1, 0, xxyx);
vector_swizzle_quadruple!(3, 0, 0, 1, 0, uuvu);
vector_swizzle_quadruple!(3, 0, 0, 1, 0, ssts);
vector_swizzle_quadruple!(3, 0, 0, 1, 0, rrgr);
vector_swizzle_quadruple!(3, 0, 0, 1, 1, xxyy);
vector_swizzle_quadruple!(3, 0, 0, 1, 1, uuvv);
vector_swizzle_quadruple!(3, 0, 0, 1, 1, sstt);
vector_swizzle_quadruple!(3, 0, 0, 1, 1, rrgg);
vector_swizzle_quadruple!(3, 0, 0, 1, 2, xxyz);
vector_swizzle_quadruple!(3, 0, 0, 1, 2, sstq);
vector_swizzle_quadruple!(3, 0, 0, 1, 2, rrgb);
vector_swizzle_quadruple!(3, 0, 0, 2, 0, xxzx);
vector_swizzle_quadruple!(3, 0, 0, 2, 0, ssqs);
vector_swizzle_quadruple!(3, 0, 0, 2, 0, rrbr);
vector_swizzle_quadruple!(3, 0, 0, 2, 1, xxzy);
vector_swizzle_quadruple!(3, 0, 0, 2, 1, ssqt);
vector_swizzle_quadruple!(3, 0, 0, 2, 1, rrbg);
vector_swizzle_quadruple!(3, 0, 0, 2, 2, xxzz);
vector_swizzle_quadruple!(3, 0, 0, 2, 2, ssqq);
vector_swizzle_quadruple!(3, 0, 0, 2, 2, rrbb);
vector_swizzle_quadruple!(3, 0, 1, 0, 0, xyxx);
vector_swizzle_quadruple!(3, 0, 1, 0, 0, uvuu);
vector_swizzle_quadruple!(3, 0, 1, 0, 0, stss);
vector_swizzle_quadruple!(3, 0, 1, 0, 0, rgrr);
vector_swizzle_quadruple!(3, 0, 1, 0, 1, xyxy);
vector_swizzle_quadruple!(3, 0, 1, 0, 1, uvuv);
vector_swizzle_quadruple!(3, 0, 1, 0, 1, stst);
vector_swizzle_quadruple!(3, 0, 1, 0, 1, rgrg);
vector_swizzle_quadruple!(3, 0, 1, 0, 2, xyxz);
vector_swizzle_quadruple!(3, 0, 1, 0, 2, stsq);
vector_swizzle_quadruple!(3, 0, 1, 0, 2, rgrb);
vector_swizzle_quadruple!(3, 0, 1, 1, 0, xyyx);
vector_swizzle_quadruple!(3, 0, 1, 1, 0, uvvu);
vector_swizzle_quadruple!(3, 0, 1, 1, 0, stts);
vector_swizzle_quadruple!(3, 0, 1, 1, 0, rggr);
vector_swizzle_quadruple!(3, 0, 1, 1, 1, xyyy);
vector_swizzle_quadruple!(3, 0, 1, 1, 1, uvvv);
vector_swizzle_quadruple!(3, 0, 1, 1, 1, sttt);
vector_swizzle_quadruple!(3, 0, 1, 1, 1, rggg);
vector_swizzle_quadruple!(3, 0, 1, 1, 2, xyyz);
vector_swizzle_quadruple!(3, 0, 1, 1, 2, sttq);
vector_swizzle_quadruple!(3, 0, 1, 1, 2, rggb);
vector_swizzle_quadruple!(3, 0, 1, 2, 0, xyzx);
vector_swizzle_quadruple!(3, 0, 1, 2, 0, stqs);
vector_swizzle_quadruple!(3, 0, 1, 2, 0, rgbr);
vector_swizzle_quadruple!(3, 0, 1, 2, 1, xyzy);
vector_swizzle_quadruple!(3, 0, 1, 2, 1, stqt);
vector_swizzle_quadruple!(3, 0, 1, 2, 1, rgbg);
vector_swizzle_quadruple!(3, 0, 1, 2, 2, xyzz);
vector_swizzle_quadruple!(3, 0, 1, 2, 2, stqq);
vector_swizzle_quadruple!(3, 0, 1, 2, 2, rgbb);
vector_swizzle_quadruple!(3, 0, 2, 0, 0, xzxx);
vector_swizzle_quadruple!(3, 0, 2, 0, 0, sqss);
vector_swizzle_quadruple!(3, 0, 2, 0, 0, rbrr);
vector_swizzle_quadruple!(3, 0, 2, 0, 1, xzxy);
vector_swizzle_quadruple!(3, 0, 2, 0, 1, sqst);
vector_swizzle_quadruple!(3, 0, 2, 0, 1, rbrg);
vector_swizzle_quadruple!(3, 0, 2, 0, 2, xzxz);
vector_swizzle_quadruple!(3, 0, 2, 0, 2, sqsq);
vector_swizzle_quadruple!(3, 0, 2, 0, 2, rbrb);
vector_swizzle_quadruple!(3, 0, 2, 1, 0, xzyx);
vector_swizzle_quadruple!(3, 0, 2, 1, 0, sqts);
vector_swizzle_quadruple!(3, 0, 2, 1, 0, rbgr);
vector_swizzle_quadruple!(3, 0, 2, 1, 1, xzyy);
vector_swizzle_quadruple!(3, 0, 2, 1, 1, sqtt);
vector_swizzle_quadruple!(3, 0, 2, 1, 1, rbgg);
vector_swizzle_quadruple!(3, 0, 2, 1, 2, xzyz);
vector_swizzle_quadruple!(3, 0, 2, 1, 2, sqtq);
vector_swizzle_quadruple!(3, 0, 2, 1, 2, rbgb);
vector_swizzle_quadruple!(3, 0, 2, 2, 0, xzzx);
vector_swizzle_quadruple!(3, 0, 2, 2, 0, sqqs);
vector_swizzle_quadruple!(3, 0, 2, 2, 0, rbbr);
vector_swizzle_quadruple!(3, 0, 2, 2, 1, xzzy);
vector_swizzle_quadruple!(3, 0, 2, 2, 1, sqqt);
vector_swizzle_quadruple!(3, 0, 2, 2, 1, rbbg);
vector_swizzle_quadruple!(3, 0, 2, 2, 2, xzzz);
vector_swizzle_quadruple!(3, 0, 2, 2, 2, sqqq);
vector_swizzle_quadruple!(3, 0, 2, 2, 2, rbbb);
vector_swizzle_quadruple!(3, 1, 0, 0, 0, yxxx);
vector_swizzle_quadruple!(3, 1, 0, 0, 0, vuuu);
vector_swizzle_quadruple!(3, 1, 0, 0, 0, tsss);
vector_swizzle_quadruple!(3, 1, 0, 0, 0, grrr);
vector_swizzle_quadruple!(3, 1, 0, 0, 1, yxxy);
vector_swizzle_quadruple!(3, 1, 0, 0, 1, vuuv);
vector_swizzle_quadruple!(3, 1, 0, 0, 1, tsst);
vector_swizzle_quadruple!(3, 1, 0, 0, 1, grrg);
vector_swizzle_quadruple!(3, 1, 0, 0, 2, yxxz);
vector_swizzle_quadruple!(3, 1, 0, 0, 2, tssq);
vector_swizzle_quadruple!(3, 1, 0, 0, 2, grrb);
vector_swizzle_quadruple!(3, 1, 0, 1, 0, yxyx);
vector_swizzle_quadruple!(3, 1, 0, 1, 0, vuvu);
vector_swizzle_quadruple!(3, 1, 0, 1, 0, tsts);
vector_swizzle_quadruple!(3, 1, 0, 1, 0, grgr);
vector_swizzle_quadruple!(3, 1, 0, 1, 1, yxyy);
vector_swizzle_quadruple!(3, 1, 0, 1, 1, vuvv);
vector_swizzle_quadruple!(3, 1, 0, 1, 1, tstt);
vector_swizzle_quadruple!(3, 1, 0, 1, 1, grgg);
vector_swizzle_quadruple!(3, 1, 0, 1, 2, yxyz);
vector_swizzle_quadruple!(3, 1, 0, 1, 2, tstq);
vector_swizzle_quadruple!(3, 1, 0, 1, 2, grgb);
vector_swizzle_quadruple!(3, 1, 0, 2, 0, yxzx);
vector_swizzle_quadruple!(3, 1, 0, 2, 0, tsqs);
vector_swizzle_quadruple!(3, 1, 0, 2, 0, grbr);
vector_swizzle_quadruple!(3, 1, 0, 2, 1, yxzy);
vector_swizzle_quadruple!(3, 1, 0, 2, 1, tsqt);
vector_swizzle_quadruple!(3, 1, 0, 2, 1, grbg);
vector_swizzle_quadruple!(3, 1, 0, 2, 2, yxzz);
vector_swizzle_quadruple!(3, 1, 0, 2, 2, tsqq);
vector_swizzle_quadruple!(3, 1, 0, 2, 2, grbb);
vector_swizzle_quadruple!(3, 1, 1, 0, 0, yyxx);
vector_swizzle_quadruple!(3, 1, 1, 0, 0, vvuu);
vector_swizzle_quadruple!(3, 1, 1, 0, 0, ttss);
vector_swizzle_quadruple!(3, 1, 1, 0, 0, ggrr);
vector_swizzle_quadruple!(3, 1, 1, 0, 1, yyxy);
vector_swizzle_quadruple!(3, 1, 1, 0, 1, vvuv);
vector_swizzle_quadruple!(3, 1, 1, 0, 1, ttst);
vector_swizzle_quadruple!(3, 1, 1, 0, 1, ggrg);
vector_swizzle_quadruple!(3, 1, 1, 0, 2, yyxz);
vector_swizzle_quadruple!(3, 1, 1, 0, 2, ttsq);
vector_swizzle_quadruple!(3, 1, 1, 0, 2, ggrb);
vector_swizzle_quadruple!(3, 1, 1, 1, 0, yyyx);
vector_swizzle_quadruple!(3, 1, 1, 1, 0, vvvu);
vector_swizzle_quadruple!(3, 1, 1, 1, 0, ttts);
vector_swizzle_quadruple!(3, 1, 1, 1, 0, gggr);
vector_swizzle_quadruple!(3, 1, 1, 1, 1, yyyy);
vector_swizzle_quadruple!(3, 1, 1, 1, 1, vvvv);
vector_swizzle_quadruple!(3, 1, 1, 1, 1, tttt);
vector_swizzle_quadruple!(3, 1, 1, 1, 1, gggg);
vector_swizzle_quadruple!(3, 1, 1, 1, 2, yyyz);
vector_swizzle_quadruple!(3, 1, 1, 1, 2, tttq);
vector_swizzle_quadruple!(3, 1, 1, 1, 2, gggb);
vector_swizzle_quadruple!(3, 1, 1, 2, 0, yyzx);
vector_swizzle_quadruple!(3, 1, 1, 2, 0, ttqs);
vector_swizzle_quadruple!(3, 1, 1, 2, 0, ggbr);
vector_swizzle_quadruple!(3, 1, 1, 2, 1, yyzy);
vector_swizzle_quadruple!(3, 1, 1, 2, 1, ttqt);
vector_swizzle_quadruple!(3, 1, 1, 2, 1, ggbg);
vector_swizzle_quadruple!(3, 1, 1, 2, 2, yyzz);
vector_swizzle_quadruple!(3, 1, 1, 2, 2, ttqq);
vector_swizzle_quadruple!(3, 1, 1, 2, 2, ggbb);
vector_swizzle_quadruple!(3, 1, 2, 0, 0, yzxx);
vector_swizzle_quadruple!(3, 1, 2, 0, 0, tqss);
vector_swizzle_quadruple!(3, 1, 2, 0, 0, gbrr);
vector_swizzle_quadruple!(3, 1, 2, 0, 1, yzxy);
vector_swizzle_quadruple!(3, 1, 2, 0, 1, tqst);
vector_swizzle_quadruple!(3, 1, 2, 0, 1, gbrg);
vector_swizzle_quadruple!(3, 1, 2, 0, 2, yzxz);
vector_swizzle_quadruple!(3, 1, 2, 0, 2, tqsq);
vector_swizzle_quadruple!(3, 1, 2, 0, 2, gbrb);
vector_swizzle_quadruple!(3, 1, 2, 1, 0, yzyx);
vector_swizzle_quadruple!(3, 1, 2, 1, 0, tqts);
vector_swizzle_quadruple!(3, 1, 2, 1, 0, gbgr);
vector_swizzle_quadruple!(3, 1, 2, 1, 1, yzyy);
vector_swizzle_quadruple!(3, 1, 2, 1, 1, tqtt);
vector_swizzle_quadruple!(3, 1, 2, 1, 1, gbgg);
vector_swizzle_quadruple!(3, 1, 2, 1, 2, yzyz);
vector_swizzle_quadruple!(3, 1, 2, 1, 2, tqtq);
vector_swizzle_quadruple!(3, 1, 2, 1, 2, gbgb);
vector_swizzle_quadruple!(3, 1, 2, 2, 0, yzzx);
vector_swizzle_quadruple!(3, 1, 2, 2, 0, tqqs);
vector_swizzle_quadruple!(3, 1, 2, 2, 0, gbbr);
vector_swizzle_quadruple!(3, 1, 2, 2, 1, yzzy);
vector_swizzle_quadruple!(3, 1, 2, 2, 1, tqqt);
vector_swizzle_quadruple!(3, 1, 2, 2, 1, gbbg);
vector_swizzle_quadruple!(3, 1, 2, 2, 2, yzzz);
vector_swizzle_quadruple!(3, 1, 2, 2, 2, tqqq);
vector_swizzle_quadruple!(3, 1, 2, 2, 2, gbbb);
vector_swizzle_quadruple!(3, 2, 0, 0, 0, zxxx);
vector_swizzle_quadruple!(3, 2, 0, 0, 0, qsss);
vector_swizzle_quadruple!(3, 2, 0, 0, 0, brrr);
vector_swizzle_quadruple!(3, 2, 0, 0, 1, zxxy);
vector_swizzle_quadruple!(3, 2, 0, 0, 1, qsst);
vector_swizzle_quadruple!(3, 2, 0, 0, 1, brrg);
vector_swizzle_quadruple!(3, 2, 0, 0, 2, zxxz);
vector_swizzle_quadruple!(3, 2, 0, 0, 2, qssq);
vector_swizzle_quadruple!(3, 2, 0, 0, 2, brrb);
vector_swizzle_quadruple!(3, 2, 0, 1, 0, zxyx);
vector_swizzle_quadruple!(3, 2, 0, 1, 0, qsts);
vector_swizzle_quadruple!(3, 2, 0, 1, 0, brgr);
vector_swizzle_quadruple!(3, 2, 0, 1, 1, zxyy);
vector_swizzle_quadruple!(3, 2, 0, 1, 1, qstt);
vector_swizzle_quadruple!(3, 2, 0, 1, 1, brgg);
vector_swizzle_quadruple!(3, 2, 0, 1, 2, zxyz);
vector_swizzle_quadruple!(3, 2, 0, 1, 2, qstq);
vector_swizzle_quadruple!(3, 2, 0, 1, 2, brgb);
vector_swizzle_quadruple!(3, 2, 0, 2, 0, zxzx);
vector_swizzle_quadruple!(3, 2, 0, 2, 0, qsqs);
vector_swizzle_quadruple!(3, 2, 0, 2, 0, brbr);
vector_swizzle_quadruple!(3, 2, 0, 2, 1, zxzy);
vector_swizzle_quadruple!(3, 2, 0, 2, 1, qsqt);
vector_swizzle_quadruple!(3, 2, 0, 2, 1, brbg);
vector_swizzle_quadruple!(3, 2, 0, 2, 2, zxzz);
vector_swizzle_quadruple!(3, 2, 0, 2, 2, qsqq);
vector_swizzle_quadruple!(3, 2, 0, 2, 2, brbb);
vector_swizzle_quadruple!(3, 2, 1, 0, 0, zyxx);
vector_swizzle_quadruple!(3, 2, 1, 0, 0, qtss);
vector_swizzle_quadruple!(3, 2, 1, 0, 0, bgrr);
vector_swizzle_quadruple!(3, 2, 1, 0, 1, zyxy);
vector_swizzle_quadruple!(3, 2, 1, 0, 1, qtst);
vector_swizzle_quadruple!(3, 2, 1, 0, 1, bgrg);
vector_swizzle_quadruple!(3, 2, 1, 0, 2, zyxz);
vector_swizzle_quadruple!(3, 2, 1, 0, 2, qtsq);
vector_swizzle_quadruple!(3, 2, 1, 0, 2, bgrb);
vector_swizzle_quadruple!(3, 2, 1, 1, 0, zyyx);
vector_swizzle_quadruple!(3, 2, 1, 1, 0, qtts);
vector_swizzle_quadruple!(3, 2, 1, 1, 0, bggr);
vector_swizzle_quadruple!(3, 2, 1, 1, 1, zyyy);
vector_swizzle_quadruple!(3, 2, 1, 1, 1, qttt);
vector_swizzle_quadruple!(3, 2, 1, 1, 1, bggg);
vector_swizzle_quadruple!(3, 2, 1, 1, 2, zyyz);
vector_swizzle_quadruple!(3, 2, 1, 1, 2, qttq);
vector_swizzle_quadruple!(3, 2, 1, 1, 2, bggb);
vector_swizzle_quadruple!(3, 2, 1, 2, 0, zyzx);
vector_swizzle_quadruple!(3, 2, 1, 2, 0, qtqs);
vector_swizzle_quadruple!(3, 2, 1, 2, 0, bgbr);
vector_swizzle_quadruple!(3, 2, 1, 2, 1, zyzy);
vector_swizzle_quadruple!(3, 2, 1, 2, 1, qtqt);
vector_swizzle_quadruple!(3, 2, 1, 2, 1, bgbg);
vector_swizzle_quadruple!(3, 2, 1, 2, 2, zyzz);
vector_swizzle_quadruple!(3, 2, 1, 2, 2, qtqq);
vector_swizzle_quadruple!(3, 2, 1, 2, 2, bgbb);
vector_swizzle_quadruple!(3, 2, 2, 0, 0, zzxx);
vector_swizzle_quadruple!(3, 2, 2, 0, 0, qqss);
vector_swizzle_quadruple!(3, 2, 2, 0, 0, bbrr);
vector_swizzle_quadruple!(3, 2, 2, 0, 1, zzxy);
vector_swizzle_quadruple!(3, 2, 2, 0, 1, qqst);
vector_swizzle_quadruple!(3, 2, 2, 0, 1, bbrg);
vector_swizzle_quadruple!(3, 2, 2, 0, 2, zzxz);
vector_swizzle_quadruple!(3, 2, 2, 0, 2, qqsq);
vector_swizzle_quadruple!(3, 2, 2, 0, 2, bbrb);
vector_swizzle_quadruple!(3, 2, 2, 1, 0, zzyx);
vector_swizzle_quadruple!(3, 2, 2, 1, 0, qqts);
vector_swizzle_quadruple!(3, 2, 2, 1, 0, bbgr);
vector_swizzle_quadruple!(3, 2, 2, 1, 1, zzyy);
vector_swizzle_quadruple!(3, 2, 2, 1, 1, qqtt);
vector_swizzle_quadruple!(3, 2, 2, 1, 1, bbgg);
vector_swizzle_quadruple!(3, 2, 2, 1, 2, zzyz);
vector_swizzle_quadruple!(3, 2, 2, 1, 2, qqtq);
vector_swizzle_quadruple!(3, 2, 2, 1, 2, bbgb);
vector_swizzle_quadruple!(3, 2, 2, 2, 0, zzzx);
vector_swizzle_quadruple!(3, 2, 2, 2, 0, qqqs);
vector_swizzle_quadruple!(3, 2, 2, 2, 0, bbbr);
vector_swizzle_quadruple!(3, 2, 2, 2, 1, zzzy);
vector_swizzle_quadruple!(3, 2, 2, 2, 1, qqqt);
vector_swizzle_quadruple!(3, 2, 2, 2, 1, bbbg);
vector_swizzle_quadruple!(3, 2, 2, 2, 2, zzzz);
vector_swizzle_quadruple!(3, 2, 2, 2, 2, qqqq);
vector_swizzle_quadruple!(3, 2, 2, 2, 2, bbbb);
// ---------------------

// VECTOR4 SWIZZLE BLOCK
vector_swizzle_single!(4, 0, x);
vector_swizzle_single!(4, 0, u);
vector_swizzle_single!(4, 0, s);
vector_swizzle_single!(4, 0, r);
vector_swizzle_single!(4, 1, y);
vector_swizzle_single!(4, 1, v);
vector_swizzle_single!(4, 1, t);
vector_swizzle_single!(4, 1, g);
vector_swizzle_single!(4, 2, z);
vector_swizzle_single!(4, 2, q);
vector_swizzle_single!(4, 2, b);
vector_swizzle_single!(4, 3, w);
vector_swizzle_single!(4, 3, a);
vector_swizzle_double!(4, 0, 0, xx);
vector_swizzle_double!(4, 0, 0, uu);
vector_swizzle_double!(4, 0, 0, ss);
vector_swizzle_double!(4, 0, 0, rr);
vector_swizzle_double!(4, 0, 1, xy);
vector_swizzle_double!(4, 0, 1, uv);
vector_swizzle_double!(4, 0, 1, st);
vector_swizzle_double!(4, 0, 1, rg);
vector_swizzle_double!(4, 0, 2, xz);
vector_swizzle_double!(4, 0, 2, sq);
vector_swizzle_double!(4, 0, 2, rb);
vector_swizzle_double!(4, 0, 3, xw);
vector_swizzle_double!(4, 0, 3, ra);
vector_swizzle_double!(4, 1, 0, yx);
vector_swizzle_double!(4, 1, 0, vu);
vector_swizzle_double!(4, 1, 0, ts);
vector_swizzle_double!(4, 1, 0, gr);
vector_swizzle_double!(4, 1, 1, yy);
vector_swizzle_double!(4, 1, 1, vv);
vector_swizzle_double!(4, 1, 1, tt);
vector_swizzle_double!(4, 1, 1, gg);
vector_swizzle_double!(4, 1, 2, yz);
vector_swizzle_double!(4, 1, 2, tq);
vector_swizzle_double!(4, 1, 2, gb);
vector_swizzle_double!(4, 1, 3, yw);
vector_swizzle_double!(4, 1, 3, ga);
vector_swizzle_double!(4, 2, 0, zx);
vector_swizzle_double!(4, 2, 0, qs);
vector_swizzle_double!(4, 2, 0, br);
vector_swizzle_double!(4, 2, 1, zy);
vector_swizzle_double!(4, 2, 1, qt);
vector_swizzle_double!(4, 2, 1, bg);
vector_swizzle_double!(4, 2, 2, zz);
vector_swizzle_double!(4, 2, 2, qq);
vector_swizzle_double!(4, 2, 2, bb);
vector_swizzle_double!(4, 2, 3, zw);
vector_swizzle_double!(4, 2, 3, ba);
vector_swizzle_double!(4, 3, 0, wx);
vector_swizzle_double!(4, 3, 0, ar);
vector_swizzle_double!(4, 3, 1, wy);
vector_swizzle_double!(4, 3, 1, ag);
vector_swizzle_double!(4, 3, 2, wz);
vector_swizzle_double!(4, 3, 2, ab);
vector_swizzle_double!(4, 3, 3, ww);
vector_swizzle_double!(4, 3, 3, aa);
vector_swizzle_triple!(4, 0, 0, 0, xxx);
vector_swizzle_triple!(4, 0, 0, 0, uuu);
vector_swizzle_triple!(4, 0, 0, 0, sss);
vector_swizzle_triple!(4, 0, 0, 0, rrr);
vector_swizzle_triple!(4, 0, 0, 1, xxy);
vector_swizzle_triple!(4, 0, 0, 1, uuv);
vector_swizzle_triple!(4, 0, 0, 1, sst);
vector_swizzle_triple!(4, 0, 0, 1, rrg);
vector_swizzle_triple!(4, 0, 0, 2, xxz);
vector_swizzle_triple!(4, 0, 0, 2, ssq);
vector_swizzle_triple!(4, 0, 0, 2, rrb);
vector_swizzle_triple!(4, 0, 0, 3, xxw);
vector_swizzle_triple!(4, 0, 0, 3, rra);
vector_swizzle_triple!(4, 0, 1, 0, xyx);
vector_swizzle_triple!(4, 0, 1, 0, uvu);
vector_swizzle_triple!(4, 0, 1, 0, sts);
vector_swizzle_triple!(4, 0, 1, 0, rgr);
vector_swizzle_triple!(4, 0, 1, 1, xyy);
vector_swizzle_triple!(4, 0, 1, 1, uvv);
vector_swizzle_triple!(4, 0, 1, 1, stt);
vector_swizzle_triple!(4, 0, 1, 1, rgg);
vector_swizzle_triple!(4, 0, 1, 2, xyz);
vector_swizzle_triple!(4, 0, 1, 2, stq);
vector_swizzle_triple!(4, 0, 1, 2, rgb);
vector_swizzle_triple!(4, 0, 1, 3, xyw);
vector_swizzle_triple!(4, 0, 1, 3, rga);
vector_swizzle_triple!(4, 0, 2, 0, xzx);
vector_swizzle_triple!(4, 0, 2, 0, sqs);
vector_swizzle_triple!(4, 0, 2, 0, rbr);
vector_swizzle_triple!(4, 0, 2, 1, xzy);
vector_swizzle_triple!(4, 0, 2, 1, sqt);
vector_swizzle_triple!(4, 0, 2, 1, rbg);
vector_swizzle_triple!(4, 0, 2, 2, xzz);
vector_swizzle_triple!(4, 0, 2, 2, sqq);
vector_swizzle_triple!(4, 0, 2, 2, rbb);
vector_swizzle_triple!(4, 0, 2, 3, xzw);
vector_swizzle_triple!(4, 0, 2, 3, rba);
vector_swizzle_triple!(4, 0, 3, 0, xwx);
vector_swizzle_triple!(4, 0, 3, 0, rar);
vector_swizzle_triple!(4, 0, 3, 1, xwy);
vector_swizzle_triple!(4, 0, 3, 1, rag);
vector_swizzle_triple!(4, 0, 3, 2, xwz);
vector_swizzle_triple!(4, 0, 3, 2, rab);
vector_swizzle_triple!(4, 0, 3, 3, xww);
vector_swizzle_triple!(4, 0, 3, 3, raa);
vector_swizzle_triple!(4, 1, 0, 0, yxx);
vector_swizzle_triple!(4, 1, 0, 0, vuu);
vector_swizzle_triple!(4, 1, 0, 0, tss);
vector_swizzle_triple!(4, 1, 0, 0, grr);
vector_swizzle_triple!(4, 1, 0, 1, yxy);
vector_swizzle_triple!(4, 1, 0, 1, vuv);
vector_swizzle_triple!(4, 1, 0, 1, tst);
vector_swizzle_triple!(4, 1, 0, 1, grg);
vector_swizzle_triple!(4, 1, 0, 2, yxz);
vector_swizzle_triple!(4, 1, 0, 2, tsq);
vector_swizzle_triple!(4, 1, 0, 2, grb);
vector_swizzle_triple!(4, 1, 0, 3, yxw);
vector_swizzle_triple!(4, 1, 0, 3, gra);
vector_swizzle_triple!(4, 1, 1, 0, yyx);
vector_swizzle_triple!(4, 1, 1, 0, vvu);
vector_swizzle_triple!(4, 1, 1, 0, tts);
vector_swizzle_triple!(4, 1, 1, 0, ggr);
vector_swizzle_triple!(4, 1, 1, 1, yyy);
vector_swizzle_triple!(4, 1, 1, 1, vvv);
vector_swizzle_triple!(4, 1, 1, 1, ttt);
vector_swizzle_triple!(4, 1, 1, 1, ggg);
vector_swizzle_triple!(4, 1, 1, 2, yyz);
vector_swizzle_triple!(4, 1, 1, 2, ttq);
vector_swizzle_triple!(4, 1, 1, 2, ggb);
vector_swizzle_triple!(4, 1, 1, 3, yyw);
vector_swizzle_triple!(4, 1, 1, 3, gga);
vector_swizzle_triple!(4, 1, 2, 0, yzx);
vector_swizzle_triple!(4, 1, 2, 0, tqs);
vector_swizzle_triple!(4, 1, 2, 0, gbr);
vector_swizzle_triple!(4, 1, 2, 1, yzy);
vector_swizzle_triple!(4, 1, 2, 1, tqt);
vector_swizzle_triple!(4, 1, 2, 1, gbg);
vector_swizzle_triple!(4, 1, 2, 2, yzz);
vector_swizzle_triple!(4, 1, 2, 2, tqq);
vector_swizzle_triple!(4, 1, 2, 2, gbb);
vector_swizzle_triple!(4, 1, 2, 3, yzw);
vector_swizzle_triple!(4, 1, 2, 3, gba);
vector_swizzle_triple!(4, 1, 3, 0, ywx);
vector_swizzle_triple!(4, 1, 3, 0, gar);
vector_swizzle_triple!(4, 1, 3, 1, ywy);
vector_swizzle_triple!(4, 1, 3, 1, gag);
vector_swizzle_triple!(4, 1, 3, 2, ywz);
vector_swizzle_triple!(4, 1, 3, 2, gab);
vector_swizzle_triple!(4, 1, 3, 3, yww);
vector_swizzle_triple!(4, 1, 3, 3, gaa);
vector_swizzle_triple!(4, 2, 0, 0, zxx);
vector_swizzle_triple!(4, 2, 0, 0, qss);
vector_swizzle_triple!(4, 2, 0, 0, brr);
vector_swizzle_triple!(4, 2, 0, 1, zxy);
vector_swizzle_triple!(4, 2, 0, 1, qst);
vector_swizzle_triple!(4, 2, 0, 1, brg);
vector_swizzle_triple!(4, 2, 0, 2, zxz);
vector_swizzle_triple!(4, 2, 0, 2, qsq);
vector_swizzle_triple!(4, 2, 0, 2, brb);
vector_swizzle_triple!(4, 2, 0, 3, zxw);
vector_swizzle_triple!(4, 2, 0, 3, bra);
vector_swizzle_triple!(4, 2, 1, 0, zyx);
vector_swizzle_triple!(4, 2, 1, 0, qts);
vector_swizzle_triple!(4, 2, 1, 0, bgr);
vector_swizzle_triple!(4, 2, 1, 1, zyy);
vector_swizzle_triple!(4, 2, 1, 1, qtt);
vector_swizzle_triple!(4, 2, 1, 1, bgg);
vector_swizzle_triple!(4, 2, 1, 2, zyz);
vector_swizzle_triple!(4, 2, 1, 2, qtq);
vector_swizzle_triple!(4, 2, 1, 2, bgb);
vector_swizzle_triple!(4, 2, 1, 3, zyw);
vector_swizzle_triple!(4, 2, 1, 3, bga);
vector_swizzle_triple!(4, 2, 2, 0, zzx);
vector_swizzle_triple!(4, 2, 2, 0, qqs);
vector_swizzle_triple!(4, 2, 2, 0, bbr);
vector_swizzle_triple!(4, 2, 2, 1, zzy);
vector_swizzle_triple!(4, 2, 2, 1, qqt);
vector_swizzle_triple!(4, 2, 2, 1, bbg);
vector_swizzle_triple!(4, 2, 2, 2, zzz);
vector_swizzle_triple!(4, 2, 2, 2, qqq);
vector_swizzle_triple!(4, 2, 2, 2, bbb);
vector_swizzle_triple!(4, 2, 2, 3, zzw);
vector_swizzle_triple!(4, 2, 2, 3, bba);
vector_swizzle_triple!(4, 2, 3, 0, zwx);
vector_swizzle_triple!(4, 2, 3, 0, bar);
vector_swizzle_triple!(4, 2, 3, 1, zwy);
vector_swizzle_triple!(4, 2, 3, 1, bag);
vector_swizzle_triple!(4, 2, 3, 2, zwz);
vector_swizzle_triple!(4, 2, 3, 2, bab);
vector_swizzle_triple!(4, 2, 3, 3, zww);
vector_swizzle_triple!(4, 2, 3, 3, baa);
vector_swizzle_triple!(4, 3, 0, 0, wxx);
vector_swizzle_triple!(4, 3, 0, 0, arr);
vector_swizzle_triple!(4, 3, 0, 1, wxy);
vector_swizzle_triple!(4, 3, 0, 1, arg);
vector_swizzle_triple!(4, 3, 0, 2, wxz);
vector_swizzle_triple!(4, 3, 0, 2, arb);
vector_swizzle_triple!(4, 3, 0, 3, wxw);
vector_swizzle_triple!(4, 3, 0, 3, ara);
vector_swizzle_triple!(4, 3, 1, 0, wyx);
vector_swizzle_triple!(4, 3, 1, 0, agr);
vector_swizzle_triple!(4, 3, 1, 1, wyy);
vector_swizzle_triple!(4, 3, 1, 1, agg);
vector_swizzle_triple!(4, 3, 1, 2, wyz);
vector_swizzle_triple!(4, 3, 1, 2, agb);
vector_swizzle_triple!(4, 3, 1, 3, wyw);
vector_swizzle_triple!(4, 3, 1, 3, aga);
vector_swizzle_triple!(4, 3, 2, 0, wzx);
vector_swizzle_triple!(4, 3, 2, 0, abr);
vector_swizzle_triple!(4, 3, 2, 1, wzy);
vector_swizzle_triple!(4, 3, 2, 1, abg);
vector_swizzle_triple!(4, 3, 2, 2, wzz);
vector_swizzle_triple!(4, 3, 2, 2, abb);
vector_swizzle_triple!(4, 3, 2, 3, wzw);
vector_swizzle_triple!(4, 3, 2, 3, aba);
vector_swizzle_triple!(4, 3, 3, 0, wwx);
vector_swizzle_triple!(4, 3, 3, 0, aar);
vector_swizzle_triple!(4, 3, 3, 1, wwy);
vector_swizzle_triple!(4, 3, 3, 1, aag);
vector_swizzle_triple!(4, 3, 3, 2, wwz);
vector_swizzle_triple!(4, 3, 3, 2, aab);
vector_swizzle_triple!(4, 3, 3, 3, www);
vector_swizzle_triple!(4, 3, 3, 3, aaa);
vector_swizzle_quadruple!(4, 0, 0, 0, 0, xxxx);
vector_swizzle_quadruple!(4, 0, 0, 0, 0, uuuu);
vector_swizzle_quadruple!(4, 0, 0, 0, 0, ssss);
vector_swizzle_quadruple!(4, 0, 0, 0, 0, rrrr);
vector_swizzle_quadruple!(4, 0, 0, 0, 1, xxxy);
vector_swizzle_quadruple!(4, 0, 0, 0, 1, uuuv);
vector_swizzle_quadruple!(4, 0, 0, 0, 1, ssst);
vector_swizzle_quadruple!(4, 0, 0, 0, 1, rrrg);
vector_swizzle_quadruple!(4, 0, 0, 0, 2, xxxz);
vector_swizzle_quadruple!(4, 0, 0, 0, 2, sssq);
vector_swizzle_quadruple!(4, 0, 0, 0, 2, rrrb);
vector_swizzle_quadruple!(4, 0, 0, 0, 3, xxxw);
vector_swizzle_quadruple!(4, 0, 0, 0, 3, rrra);
vector_swizzle_quadruple!(4, 0, 0, 1, 0, xxyx);
vector_swizzle_quadruple!(4, 0, 0, 1, 0, uuvu);
vector_swizzle_quadruple!(4, 0, 0, 1, 0, ssts);
vector_swizzle_quadruple!(4, 0, 0, 1, 0, rrgr);
vector_swizzle_quadruple!(4, 0, 0, 1, 1, xxyy);
vector_swizzle_quadruple!(4, 0, 0, 1, 1, uuvv);
vector_swizzle_quadruple!(4, 0, 0, 1, 1, sstt);
vector_swizzle_quadruple!(4, 0, 0, 1, 1, rrgg);
vector_swizzle_quadruple!(4, 0, 0, 1, 2, xxyz);
vector_swizzle_quadruple!(4, 0, 0, 1, 2, sstq);
vector_swizzle_quadruple!(4, 0, 0, 1, 2, rrgb);
vector_swizzle_quadruple!(4, 0, 0, 1, 3, xxyw);
vector_swizzle_quadruple!(4, 0, 0, 1, 3, rrga);
vector_swizzle_quadruple!(4, 0, 0, 2, 0, xxzx);
vector_swizzle_quadruple!(4, 0, 0, 2, 0, ssqs);
vector_swizzle_quadruple!(4, 0, 0, 2, 0, rrbr);
vector_swizzle_quadruple!(4, 0, 0, 2, 1, xxzy);
vector_swizzle_quadruple!(4, 0, 0, 2, 1, ssqt);
vector_swizzle_quadruple!(4, 0, 0, 2, 1, rrbg);
vector_swizzle_quadruple!(4, 0, 0, 2, 2, xxzz);
vector_swizzle_quadruple!(4, 0, 0, 2, 2, ssqq);
vector_swizzle_quadruple!(4, 0, 0, 2, 2, rrbb);
vector_swizzle_quadruple!(4, 0, 0, 2, 3, xxzw);
vector_swizzle_quadruple!(4, 0, 0, 2, 3, rrba);
vector_swizzle_quadruple!(4, 0, 0, 3, 0, xxwx);
vector_swizzle_quadruple!(4, 0, 0, 3, 0, rrar);
vector_swizzle_quadruple!(4, 0, 0, 3, 1, xxwy);
vector_swizzle_quadruple!(4, 0, 0, 3, 1, rrag);
vector_swizzle_quadruple!(4, 0, 0, 3, 2, xxwz);
vector_swizzle_quadruple!(4, 0, 0, 3, 2, rrab);
vector_swizzle_quadruple!(4, 0, 0, 3, 3, xxww);
vector_swizzle_quadruple!(4, 0, 0, 3, 3, rraa);
vector_swizzle_quadruple!(4, 0, 1, 0, 0, xyxx);
vector_swizzle_quadruple!(4, 0, 1, 0, 0, uvuu);
vector_swizzle_quadruple!(4, 0, 1, 0, 0, stss);
vector_swizzle_quadruple!(4, 0, 1, 0, 0, rgrr);
vector_swizzle_quadruple!(4, 0, 1, 0, 1, xyxy);
vector_swizzle_quadruple!(4, 0, 1, 0, 1, uvuv);
vector_swizzle_quadruple!(4, 0, 1, 0, 1, stst);
vector_swizzle_quadruple!(4, 0, 1, 0, 1, rgrg);
vector_swizzle_quadruple!(4, 0, 1, 0, 2, xyxz);
vector_swizzle_quadruple!(4, 0, 1, 0, 2, stsq);
vector_swizzle_quadruple!(4, 0, 1, 0, 2, rgrb);
vector_swizzle_quadruple!(4, 0, 1, 0, 3, xyxw);
vector_swizzle_quadruple!(4, 0, 1, 0, 3, rgra);
vector_swizzle_quadruple!(4, 0, 1, 1, 0, xyyx);
vector_swizzle_quadruple!(4, 0, 1, 1, 0, uvvu);
vector_swizzle_quadruple!(4, 0, 1, 1, 0, stts);
vector_swizzle_quadruple!(4, 0, 1, 1, 0, rggr);
vector_swizzle_quadruple!(4, 0, 1, 1, 1, xyyy);
vector_swizzle_quadruple!(4, 0, 1, 1, 1, uvvv);
vector_swizzle_quadruple!(4, 0, 1, 1, 1, sttt);
vector_swizzle_quadruple!(4, 0, 1, 1, 1, rggg);
vector_swizzle_quadruple!(4, 0, 1, 1, 2, xyyz);
vector_swizzle_quadruple!(4, 0, 1, 1, 2, sttq);
vector_swizzle_quadruple!(4, 0, 1, 1, 2, rggb);
vector_swizzle_quadruple!(4, 0, 1, 1, 3, xyyw);
vector_swizzle_quadruple!(4, 0, 1, 1, 3, rgga);
vector_swizzle_quadruple!(4, 0, 1, 2, 0, xyzx);
vector_swizzle_quadruple!(4, 0, 1, 2, 0, stqs);
vector_swizzle_quadruple!(4, 0, 1, 2, 0, rgbr);
vector_swizzle_quadruple!(4, 0, 1, 2, 1, xyzy);
vector_swizzle_quadruple!(4, 0, 1, 2, 1, stqt);
vector_swizzle_quadruple!(4, 0, 1, 2, 1, rgbg);
vector_swizzle_quadruple!(4, 0, 1, 2, 2, xyzz);
vector_swizzle_quadruple!(4, 0, 1, 2, 2, stqq);
vector_swizzle_quadruple!(4, 0, 1, 2, 2, rgbb);
vector_swizzle_quadruple!(4, 0, 1, 2, 3, xyzw);
vector_swizzle_quadruple!(4, 0, 1, 2, 3, rgba);
vector_swizzle_quadruple!(4, 0, 1, 3, 0, xywx);
vector_swizzle_quadruple!(4, 0, 1, 3, 0, rgar);
vector_swizzle_quadruple!(4, 0, 1, 3, 1, xywy);
vector_swizzle_quadruple!(4, 0, 1, 3, 1, rgag);
vector_swizzle_quadruple!(4, 0, 1, 3, 2, xywz);
vector_swizzle_quadruple!(4, 0, 1, 3, 2, rgab);
vector_swizzle_quadruple!(4, 0, 1, 3, 3, xyww);
vector_swizzle_quadruple!(4, 0, 1, 3, 3, rgaa);
vector_swizzle_quadruple!(4, 0, 2, 0, 0, xzxx);
vector_swizzle_quadruple!(4, 0, 2, 0, 0, sqss);
vector_swizzle_quadruple!(4, 0, 2, 0, 0, rbrr);
vector_swizzle_quadruple!(4, 0, 2, 0, 1, xzxy);
vector_swizzle_quadruple!(4, 0, 2, 0, 1, sqst);
vector_swizzle_quadruple!(4, 0, 2, 0, 1, rbrg);
vector_swizzle_quadruple!(4, 0, 2, 0, 2, xzxz);
vector_swizzle_quadruple!(4, 0, 2, 0, 2, sqsq);
vector_swizzle_quadruple!(4, 0, 2, 0, 2, rbrb);
vector_swizzle_quadruple!(4, 0, 2, 0, 3, xzxw);
vector_swizzle_quadruple!(4, 0, 2, 0, 3, rbra);
vector_swizzle_quadruple!(4, 0, 2, 1, 0, xzyx);
vector_swizzle_quadruple!(4, 0, 2, 1, 0, sqts);
vector_swizzle_quadruple!(4, 0, 2, 1, 0, rbgr);
vector_swizzle_quadruple!(4, 0, 2, 1, 1, xzyy);
vector_swizzle_quadruple!(4, 0, 2, 1, 1, sqtt);
vector_swizzle_quadruple!(4, 0, 2, 1, 1, rbgg);
vector_swizzle_quadruple!(4, 0, 2, 1, 2, xzyz);
vector_swizzle_quadruple!(4, 0, 2, 1, 2, sqtq);
vector_swizzle_quadruple!(4, 0, 2, 1, 2, rbgb);
vector_swizzle_quadruple!(4, 0, 2, 1, 3, xzyw);
vector_swizzle_quadruple!(4, 0, 2, 1, 3, rbga);
vector_swizzle_quadruple!(4, 0, 2, 2, 0, xzzx);
vector_swizzle_quadruple!(4, 0, 2, 2, 0, sqqs);
vector_swizzle_quadruple!(4, 0, 2, 2, 0, rbbr);
vector_swizzle_quadruple!(4, 0, 2, 2, 1, xzzy);
vector_swizzle_quadruple!(4, 0, 2, 2, 1, sqqt);
vector_swizzle_quadruple!(4, 0, 2, 2, 1, rbbg);
vector_swizzle_quadruple!(4, 0, 2, 2, 2, xzzz);
vector_swizzle_quadruple!(4, 0, 2, 2, 2, sqqq);
vector_swizzle_quadruple!(4, 0, 2, 2, 2, rbbb);
vector_swizzle_quadruple!(4, 0, 2, 2, 3, xzzw);
vector_swizzle_quadruple!(4, 0, 2, 2, 3, rbba);
vector_swizzle_quadruple!(4, 0, 2, 3, 0, xzwx);
vector_swizzle_quadruple!(4, 0, 2, 3, 0, rbar);
vector_swizzle_quadruple!(4, 0, 2, 3, 1, xzwy);
vector_swizzle_quadruple!(4, 0, 2, 3, 1, rbag);
vector_swizzle_quadruple!(4, 0, 2, 3, 2, xzwz);
vector_swizzle_quadruple!(4, 0, 2, 3, 2, rbab);
vector_swizzle_quadruple!(4, 0, 2, 3, 3, xzww);
vector_swizzle_quadruple!(4, 0, 2, 3, 3, rbaa);
vector_swizzle_quadruple!(4, 0, 3, 0, 0, xwxx);
vector_swizzle_quadruple!(4, 0, 3, 0, 0, rarr);
vector_swizzle_quadruple!(4, 0, 3, 0, 1, xwxy);
vector_swizzle_quadruple!(4, 0, 3, 0, 1, rarg);
vector_swizzle_quadruple!(4, 0, 3, 0, 2, xwxz);
vector_swizzle_quadruple!(4, 0, 3, 0, 2, rarb);
vector_swizzle_quadruple!(4, 0, 3, 0, 3, xwxw);
vector_swizzle_quadruple!(4, 0, 3, 0, 3, rara);
vector_swizzle_quadruple!(4, 0, 3, 1, 0, xwyx);
vector_swizzle_quadruple!(4, 0, 3, 1, 0, ragr);
vector_swizzle_quadruple!(4, 0, 3, 1, 1, xwyy);
vector_swizzle_quadruple!(4, 0, 3, 1, 1, ragg);
vector_swizzle_quadruple!(4, 0, 3, 1, 2, xwyz);
vector_swizzle_quadruple!(4, 0, 3, 1, 2, ragb);
vector_swizzle_quadruple!(4, 0, 3, 1, 3, xwyw);
vector_swizzle_quadruple!(4, 0, 3, 1, 3, raga);
vector_swizzle_quadruple!(4, 0, 3, 2, 0, xwzx);
vector_swizzle_quadruple!(4, 0, 3, 2, 0, rabr);
vector_swizzle_quadruple!(4, 0, 3, 2, 1, xwzy);
vector_swizzle_quadruple!(4, 0, 3, 2, 1, rabg);
vector_swizzle_quadruple!(4, 0, 3, 2, 2, xwzz);
vector_swizzle_quadruple!(4, 0, 3, 2, 2, rabb);
vector_swizzle_quadruple!(4, 0, 3, 2, 3, xwzw);
vector_swizzle_quadruple!(4, 0, 3, 2, 3, raba);
vector_swizzle_quadruple!(4, 0, 3, 3, 0, xwwx);
vector_swizzle_quadruple!(4, 0, 3, 3, 0, raar);
vector_swizzle_quadruple!(4, 0, 3, 3, 1, xwwy);
vector_swizzle_quadruple!(4, 0, 3, 3, 1, raag);
vector_swizzle_quadruple!(4, 0, 3, 3, 2, xwwz);
vector_swizzle_quadruple!(4, 0, 3, 3, 2, raab);
vector_swizzle_quadruple!(4, 0, 3, 3, 3, xwww);
vector_swizzle_quadruple!(4, 0, 3, 3, 3, raaa);
vector_swizzle_quadruple!(4, 1, 0, 0, 0, yxxx);
vector_swizzle_quadruple!(4, 1, 0, 0, 0, vuuu);
vector_swizzle_quadruple!(4, 1, 0, 0, 0, tsss);
vector_swizzle_quadruple!(4, 1, 0, 0, 0, grrr);
vector_swizzle_quadruple!(4, 1, 0, 0, 1, yxxy);
vector_swizzle_quadruple!(4, 1, 0, 0, 1, vuuv);
vector_swizzle_quadruple!(4, 1, 0, 0, 1, tsst);
vector_swizzle_quadruple!(4, 1, 0, 0, 1, grrg);
vector_swizzle_quadruple!(4, 1, 0, 0, 2, yxxz);
vector_swizzle_quadruple!(4, 1, 0, 0, 2, tssq);
vector_swizzle_quadruple!(4, 1, 0, 0, 2, grrb);
vector_swizzle_quadruple!(4, 1, 0, 0, 3, yxxw);
vector_swizzle_quadruple!(4, 1, 0, 0, 3, grra);
vector_swizzle_quadruple!(4, 1, 0, 1, 0, yxyx);
vector_swizzle_quadruple!(4, 1, 0, 1, 0, vuvu);
vector_swizzle_quadruple!(4, 1, 0, 1, 0, tsts);
vector_swizzle_quadruple!(4, 1, 0, 1, 0, grgr);
vector_swizzle_quadruple!(4, 1, 0, 1, 1, yxyy);
vector_swizzle_quadruple!(4, 1, 0, 1, 1, vuvv);
vector_swizzle_quadruple!(4, 1, 0, 1, 1, tstt);
vector_swizzle_quadruple!(4, 1, 0, 1, 1, grgg);
vector_swizzle_quadruple!(4, 1, 0, 1, 2, yxyz);
vector_swizzle_quadruple!(4, 1, 0, 1, 2, tstq);
vector_swizzle_quadruple!(4, 1, 0, 1, 2, grgb);
vector_swizzle_quadruple!(4, 1, 0, 1, 3, yxyw);
vector_swizzle_quadruple!(4, 1, 0, 1, 3, grga);
vector_swizzle_quadruple!(4, 1, 0, 2, 0, yxzx);
vector_swizzle_quadruple!(4, 1, 0, 2, 0, tsqs);
vector_swizzle_quadruple!(4, 1, 0, 2, 0, grbr);
vector_swizzle_quadruple!(4, 1, 0, 2, 1, yxzy);
vector_swizzle_quadruple!(4, 1, 0, 2, 1, tsqt);
vector_swizzle_quadruple!(4, 1, 0, 2, 1, grbg);
vector_swizzle_quadruple!(4, 1, 0, 2, 2, yxzz);
vector_swizzle_quadruple!(4, 1, 0, 2, 2, tsqq);
vector_swizzle_quadruple!(4, 1, 0, 2, 2, grbb);
vector_swizzle_quadruple!(4, 1, 0, 2, 3, yxzw);
vector_swizzle_quadruple!(4, 1, 0, 2, 3, grba);
vector_swizzle_quadruple!(4, 1, 0, 3, 0, yxwx);
vector_swizzle_quadruple!(4, 1, 0, 3, 0, grar);
vector_swizzle_quadruple!(4, 1, 0, 3, 1, yxwy);
vector_swizzle_quadruple!(4, 1, 0, 3, 1, grag);
vector_swizzle_quadruple!(4, 1, 0, 3, 2, yxwz);
vector_swizzle_quadruple!(4, 1, 0, 3, 2, grab);
vector_swizzle_quadruple!(4, 1, 0, 3, 3, yxww);
vector_swizzle_quadruple!(4, 1, 0, 3, 3, graa);
vector_swizzle_quadruple!(4, 1, 1, 0, 0, yyxx);
vector_swizzle_quadruple!(4, 1, 1, 0, 0, vvuu);
vector_swizzle_quadruple!(4, 1, 1, 0, 0, ttss);
vector_swizzle_quadruple!(4, 1, 1, 0, 0, ggrr);
vector_swizzle_quadruple!(4, 1, 1, 0, 1, yyxy);
vector_swizzle_quadruple!(4, 1, 1, 0, 1, vvuv);
vector_swizzle_quadruple!(4, 1, 1, 0, 1, ttst);
vector_swizzle_quadruple!(4, 1, 1, 0, 1, ggrg);
vector_swizzle_quadruple!(4, 1, 1, 0, 2, yyxz);
vector_swizzle_quadruple!(4, 1, 1, 0, 2, ttsq);
vector_swizzle_quadruple!(4, 1, 1, 0, 2, ggrb);
vector_swizzle_quadruple!(4, 1, 1, 0, 3, yyxw);
vector_swizzle_quadruple!(4, 1, 1, 0, 3, ggra);
vector_swizzle_quadruple!(4, 1, 1, 1, 0, yyyx);
vector_swizzle_quadruple!(4, 1, 1, 1, 0, vvvu);
vector_swizzle_quadruple!(4, 1, 1, 1, 0, ttts);
vector_swizzle_quadruple!(4, 1, 1, 1, 0, gggr);
vector_swizzle_quadruple!(4, 1, 1, 1, 1, yyyy);
vector_swizzle_quadruple!(4, 1, 1, 1, 1, vvvv);
vector_swizzle_quadruple!(4, 1, 1, 1, 1, tttt);
vector_swizzle_quadruple!(4, 1, 1, 1, 1, gggg);
vector_swizzle_quadruple!(4, 1, 1, 1, 2, yyyz);
vector_swizzle_quadruple!(4, 1, 1, 1, 2, tttq);
vector_swizzle_quadruple!(4, 1, 1, 1, 2, gggb);
vector_swizzle_quadruple!(4, 1, 1, 1, 3, yyyw);
vector_swizzle_quadruple!(4, 1, 1, 1, 3, ggga);
vector_swizzle_quadruple!(4, 1, 1, 2, 0, yyzx);
vector_swizzle_quadruple!(4, 1, 1, 2, 0, ttqs);
vector_swizzle_quadruple!(4, 1, 1, 2, 0, ggbr);
vector_swizzle_quadruple!(4, 1, 1, 2, 1, yyzy);
vector_swizzle_quadruple!(4, 1, 1, 2, 1, ttqt);
vector_swizzle_quadruple!(4, 1, 1, 2, 1, ggbg);
vector_swizzle_quadruple!(4, 1, 1, 2, 2, yyzz);
vector_swizzle_quadruple!(4, 1, 1, 2, 2, ttqq);
vector_swizzle_quadruple!(4, 1, 1, 2, 2, ggbb);
vector_swizzle_quadruple!(4, 1, 1, 2, 3, yyzw);
vector_swizzle_quadruple!(4, 1, 1, 2, 3, ggba);
vector_swizzle_quadruple!(4, 1, 1, 3, 0, yywx);
vector_swizzle_quadruple!(4, 1, 1, 3, 0, ggar);
vector_swizzle_quadruple!(4, 1, 1, 3, 1, yywy);
vector_swizzle_quadruple!(4, 1, 1, 3, 1, ggag);
vector_swizzle_quadruple!(4, 1, 1, 3, 2, yywz);
vector_swizzle_quadruple!(4, 1, 1, 3, 2, ggab);
vector_swizzle_quadruple!(4, 1, 1, 3, 3, yyww);
vector_swizzle_quadruple!(4, 1, 1, 3, 3, ggaa);
vector_swizzle_quadruple!(4, 1, 2, 0, 0, yzxx);
vector_swizzle_quadruple!(4, 1, 2, 0, 0, tqss);
vector_swizzle_quadruple!(4, 1, 2, 0, 0, gbrr);
vector_swizzle_quadruple!(4, 1, 2, 0, 1, yzxy);
vector_swizzle_quadruple!(4, 1, 2, 0, 1, tqst);
vector_swizzle_quadruple!(4, 1, 2, 0, 1, gbrg);
vector_swizzle_quadruple!(4, 1, 2, 0, 2, yzxz);
vector_swizzle_quadruple!(4, 1, 2, 0, 2, tqsq);
vector_swizzle_quadruple!(4, 1, 2, 0, 2, gbrb);
vector_swizzle_quadruple!(4, 1, 2, 0, 3, yzxw);
vector_swizzle_quadruple!(4, 1, 2, 0, 3, gbra);
vector_swizzle_quadruple!(4, 1, 2, 1, 0, yzyx);
vector_swizzle_quadruple!(4, 1, 2, 1, 0, tqts);
vector_swizzle_quadruple!(4, 1, 2, 1, 0, gbgr);
vector_swizzle_quadruple!(4, 1, 2, 1, 1, yzyy);
vector_swizzle_quadruple!(4, 1, 2, 1, 1, tqtt);
vector_swizzle_quadruple!(4, 1, 2, 1, 1, gbgg);
vector_swizzle_quadruple!(4, 1, 2, 1, 2, yzyz);
vector_swizzle_quadruple!(4, 1, 2, 1, 2, tqtq);
vector_swizzle_quadruple!(4, 1, 2, 1, 2, gbgb);
vector_swizzle_quadruple!(4, 1, 2, 1, 3, yzyw);
vector_swizzle_quadruple!(4, 1, 2, 1, 3, gbga);
vector_swizzle_quadruple!(4, 1, 2, 2, 0, yzzx);
vector_swizzle_quadruple!(4, 1, 2, 2, 0, tqqs);
vector_swizzle_quadruple!(4, 1, 2, 2, 0, gbbr);
vector_swizzle_quadruple!(4, 1, 2, 2, 1, yzzy);
vector_swizzle_quadruple!(4, 1, 2, 2, 1, tqqt);
vector_swizzle_quadruple!(4, 1, 2, 2, 1, gbbg);
vector_swizzle_quadruple!(4, 1, 2, 2, 2, yzzz);
vector_swizzle_quadruple!(4, 1, 2, 2, 2, tqqq);
vector_swizzle_quadruple!(4, 1, 2, 2, 2, gbbb);
vector_swizzle_quadruple!(4, 1, 2, 2, 3, yzzw);
vector_swizzle_quadruple!(4, 1, 2, 2, 3, gbba);
vector_swizzle_quadruple!(4, 1, 2, 3, 0, yzwx);
vector_swizzle_quadruple!(4, 1, 2, 3, 0, gbar);
vector_swizzle_quadruple!(4, 1, 2, 3, 1, yzwy);
vector_swizzle_quadruple!(4, 1, 2, 3, 1, gbag);
vector_swizzle_quadruple!(4, 1, 2, 3, 2, yzwz);
vector_swizzle_quadruple!(4, 1, 2, 3, 2, gbab);
vector_swizzle_quadruple!(4, 1, 2, 3, 3, yzww);
vector_swizzle_quadruple!(4, 1, 2, 3, 3, gbaa);
vector_swizzle_quadruple!(4, 1, 3, 0, 0, ywxx);
vector_swizzle_quadruple!(4, 1, 3, 0, 0, garr);
vector_swizzle_quadruple!(4, 1, 3, 0, 1, ywxy);
vector_swizzle_quadruple!(4, 1, 3, 0, 1, garg);
vector_swizzle_quadruple!(4, 1, 3, 0, 2, ywxz);
vector_swizzle_quadruple!(4, 1, 3, 0, 2, garb);
vector_swizzle_quadruple!(4, 1, 3, 0, 3, ywxw);
vector_swizzle_quadruple!(4, 1, 3, 0, 3, gara);
vector_swizzle_quadruple!(4, 1, 3, 1, 0, ywyx);
vector_swizzle_quadruple!(4, 1, 3, 1, 0, gagr);
vector_swizzle_quadruple!(4, 1, 3, 1, 1, ywyy);
vector_swizzle_quadruple!(4, 1, 3, 1, 1, gagg);
vector_swizzle_quadruple!(4, 1, 3, 1, 2, ywyz);
vector_swizzle_quadruple!(4, 1, 3, 1, 2, gagb);
vector_swizzle_quadruple!(4, 1, 3, 1, 3, ywyw);
vector_swizzle_quadruple!(4, 1, 3, 1, 3, gaga);
vector_swizzle_quadruple!(4, 1, 3, 2, 0, ywzx);
vector_swizzle_quadruple!(4, 1, 3, 2, 0, gabr);
vector_swizzle_quadruple!(4, 1, 3, 2, 1, ywzy);
vector_swizzle_quadruple!(4, 1, 3, 2, 1, gabg);
vector_swizzle_quadruple!(4, 1, 3, 2, 2, ywzz);
vector_swizzle_quadruple!(4, 1, 3, 2, 2, gabb);
vector_swizzle_quadruple!(4, 1, 3, 2, 3, ywzw);
vector_swizzle_quadruple!(4, 1, 3, 2, 3, gaba);
vector_swizzle_quadruple!(4, 1, 3, 3, 0, ywwx);
vector_swizzle_quadruple!(4, 1, 3, 3, 0, gaar);
vector_swizzle_quadruple!(4, 1, 3, 3, 1, ywwy);
vector_swizzle_quadruple!(4, 1, 3, 3, 1, gaag);
vector_swizzle_quadruple!(4, 1, 3, 3, 2, ywwz);
vector_swizzle_quadruple!(4, 1, 3, 3, 2, gaab);
vector_swizzle_quadruple!(4, 1, 3, 3, 3, ywww);
vector_swizzle_quadruple!(4, 1, 3, 3, 3, gaaa);
vector_swizzle_quadruple!(4, 2, 0, 0, 0, zxxx);
vector_swizzle_quadruple!(4, 2, 0, 0, 0, qsss);
vector_swizzle_quadruple!(4, 2, 0, 0, 0, brrr);
vector_swizzle_quadruple!(4, 2, 0, 0, 1, zxxy);
vector_swizzle_quadruple!(4, 2, 0, 0, 1, qsst);
vector_swizzle_quadruple!(4, 2, 0, 0, 1, brrg);
vector_swizzle_quadruple!(4, 2, 0, 0, 2, zxxz);
vector_swizzle_quadruple!(4, 2, 0, 0, 2, qssq);
vector_swizzle_quadruple!(4, 2, 0, 0, 2, brrb);
vector_swizzle_quadruple!(4, 2, 0, 0, 3, zxxw);
vector_swizzle_quadruple!(4, 2, 0, 0, 3, brra);
vector_swizzle_quadruple!(4, 2, 0, 1, 0, zxyx);
vector_swizzle_quadruple!(4, 2, 0, 1, 0, qsts);
vector_swizzle_quadruple!(4, 2, 0, 1, 0, brgr);
vector_swizzle_quadruple!(4, 2, 0, 1, 1, zxyy);
vector_swizzle_quadruple!(4, 2, 0, 1, 1, qstt);
vector_swizzle_quadruple!(4, 2, 0, 1, 1, brgg);
vector_swizzle_quadruple!(4, 2, 0, 1, 2, zxyz);
vector_swizzle_quadruple!(4, 2, 0, 1, 2, qstq);
vector_swizzle_quadruple!(4, 2, 0, 1, 2, brgb);
vector_swizzle_quadruple!(4, 2, 0, 1, 3, zxyw);
vector_swizzle_quadruple!(4, 2, 0, 1, 3, brga);
vector_swizzle_quadruple!(4, 2, 0, 2, 0, zxzx);
vector_swizzle_quadruple!(4, 2, 0, 2, 0, qsqs);
vector_swizzle_quadruple!(4, 2, 0, 2, 0, brbr);
vector_swizzle_quadruple!(4, 2, 0, 2, 1, zxzy);
vector_swizzle_quadruple!(4, 2, 0, 2, 1, qsqt);
vector_swizzle_quadruple!(4, 2, 0, 2, 1, brbg);
vector_swizzle_quadruple!(4, 2, 0, 2, 2, zxzz);
vector_swizzle_quadruple!(4, 2, 0, 2, 2, qsqq);
vector_swizzle_quadruple!(4, 2, 0, 2, 2, brbb);
vector_swizzle_quadruple!(4, 2, 0, 2, 3, zxzw);
vector_swizzle_quadruple!(4, 2, 0, 2, 3, brba);
vector_swizzle_quadruple!(4, 2, 0, 3, 0, zxwx);
vector_swizzle_quadruple!(4, 2, 0, 3, 0, brar);
vector_swizzle_quadruple!(4, 2, 0, 3, 1, zxwy);
vector_swizzle_quadruple!(4, 2, 0, 3, 1, brag);
vector_swizzle_quadruple!(4, 2, 0, 3, 2, zxwz);
vector_swizzle_quadruple!(4, 2, 0, 3, 2, brab);
vector_swizzle_quadruple!(4, 2, 0, 3, 3, zxww);
vector_swizzle_quadruple!(4, 2, 0, 3, 3, braa);
vector_swizzle_quadruple!(4, 2, 1, 0, 0, zyxx);
vector_swizzle_quadruple!(4, 2, 1, 0, 0, qtss);
vector_swizzle_quadruple!(4, 2, 1, 0, 0, bgrr);
vector_swizzle_quadruple!(4, 2, 1, 0, 1, zyxy);
vector_swizzle_quadruple!(4, 2, 1, 0, 1, qtst);
vector_swizzle_quadruple!(4, 2, 1, 0, 1, bgrg);
vector_swizzle_quadruple!(4, 2, 1, 0, 2, zyxz);
vector_swizzle_quadruple!(4, 2, 1, 0, 2, qtsq);
vector_swizzle_quadruple!(4, 2, 1, 0, 2, bgrb);
vector_swizzle_quadruple!(4, 2, 1, 0, 3, zyxw);
vector_swizzle_quadruple!(4, 2, 1, 0, 3, bgra);
vector_swizzle_quadruple!(4, 2, 1, 1, 0, zyyx);
vector_swizzle_quadruple!(4, 2, 1, 1, 0, qtts);
vector_swizzle_quadruple!(4, 2, 1, 1, 0, bggr);
vector_swizzle_quadruple!(4, 2, 1, 1, 1, zyyy);
vector_swizzle_quadruple!(4, 2, 1, 1, 1, qttt);
vector_swizzle_quadruple!(4, 2, 1, 1, 1, bggg);
vector_swizzle_quadruple!(4, 2, 1, 1, 2, zyyz);
vector_swizzle_quadruple!(4, 2, 1, 1, 2, qttq);
vector_swizzle_quadruple!(4, 2, 1, 1, 2, bggb);
vector_swizzle_quadruple!(4, 2, 1, 1, 3, zyyw);
vector_swizzle_quadruple!(4, 2, 1, 1, 3, bgga);
vector_swizzle_quadruple!(4, 2, 1, 2, 0, zyzx);
vector_swizzle_quadruple!(4, 2, 1, 2, 0, qtqs);
vector_swizzle_quadruple!(4, 2, 1, 2, 0, bgbr);
vector_swizzle_quadruple!(4, 2, 1, 2, 1, zyzy);
vector_swizzle_quadruple!(4, 2, 1, 2, 1, qtqt);
vector_swizzle_quadruple!(4, 2, 1, 2, 1, bgbg);
vector_swizzle_quadruple!(4, 2, 1, 2, 2, zyzz);
vector_swizzle_quadruple!(4, 2, 1, 2, 2, qtqq);
vector_swizzle_quadruple!(4, 2, 1, 2, 2, bgbb);
vector_swizzle_quadruple!(4, 2, 1, 2, 3, zyzw);
vector_swizzle_quadruple!(4, 2, 1, 2, 3, bgba);
vector_swizzle_quadruple!(4, 2, 1, 3, 0, zywx);
vector_swizzle_quadruple!(4, 2, 1, 3, 0, bgar);
vector_swizzle_quadruple!(4, 2, 1, 3, 1, zywy);
vector_swizzle_quadruple!(4, 2, 1, 3, 1, bgag);
vector_swizzle_quadruple!(4, 2, 1, 3, 2, zywz);
vector_swizzle_quadruple!(4, 2, 1, 3, 2, bgab);
vector_swizzle_quadruple!(4, 2, 1, 3, 3, zyww);
vector_swizzle_quadruple!(4, 2, 1, 3, 3, bgaa);
vector_swizzle_quadruple!(4, 2, 2, 0, 0, zzxx);
vector_swizzle_quadruple!(4, 2, 2, 0, 0, qqss);
vector_swizzle_quadruple!(4, 2, 2, 0, 0, bbrr);
vector_swizzle_quadruple!(4, 2, 2, 0, 1, zzxy);
vector_swizzle_quadruple!(4, 2, 2, 0, 1, qqst);
vector_swizzle_quadruple!(4, 2, 2, 0, 1, bbrg);
vector_swizzle_quadruple!(4, 2, 2, 0, 2, zzxz);
vector_swizzle_quadruple!(4, 2, 2, 0, 2, qqsq);
vector_swizzle_quadruple!(4, 2, 2, 0, 2, bbrb);
vector_swizzle_quadruple!(4, 2, 2, 0, 3, zzxw);
vector_swizzle_quadruple!(4, 2, 2, 0, 3, bbra);
vector_swizzle_quadruple!(4, 2, 2, 1, 0, zzyx);
vector_swizzle_quadruple!(4, 2, 2, 1, 0, qqts);
vector_swizzle_quadruple!(4, 2, 2, 1, 0, bbgr);
vector_swizzle_quadruple!(4, 2, 2, 1, 1, zzyy);
vector_swizzle_quadruple!(4, 2, 2, 1, 1, qqtt);
vector_swizzle_quadruple!(4, 2, 2, 1, 1, bbgg);
vector_swizzle_quadruple!(4, 2, 2, 1, 2, zzyz);
vector_swizzle_quadruple!(4, 2, 2, 1, 2, qqtq);
vector_swizzle_quadruple!(4, 2, 2, 1, 2, bbgb);
vector_swizzle_quadruple!(4, 2, 2, 1, 3, zzyw);
vector_swizzle_quadruple!(4, 2, 2, 1, 3, bbga);
vector_swizzle_quadruple!(4, 2, 2, 2, 0, zzzx);
vector_swizzle_quadruple!(4, 2, 2, 2, 0, qqqs);
vector_swizzle_quadruple!(4, 2, 2, 2, 0, bbbr);
vector_swizzle_quadruple!(4, 2, 2, 2, 1, zzzy);
vector_swizzle_quadruple!(4, 2, 2, 2, 1, qqqt);
vector_swizzle_quadruple!(4, 2, 2, 2, 1, bbbg);
vector_swizzle_quadruple!(4, 2, 2, 2, 2, zzzz);
vector_swizzle_quadruple!(4, 2, 2, 2, 2, qqqq);
vector_swizzle_quadruple!(4, 2, 2, 2, 2, bbbb);
vector_swizzle_quadruple!(4, 2, 2, 2, 3, zzzw);
vector_swizzle_quadruple!(4, 2, 2, 2, 3, bbba);
vector_swizzle_quadruple!(4, 2, 2, 3, 0, zzwx);
vector_swizzle_quadruple!(4, 2, 2, 3, 0, bbar);
vector_swizzle_quadruple!(4, 2, 2, 3, 1, zzwy);
vector_swizzle_quadruple!(4, 2, 2, 3, 1, bbag);
vector_swizzle_quadruple!(4, 2, 2, 3, 2, zzwz);
vector_swizzle_quadruple!(4, 2, 2, 3, 2, bbab);
vector_swizzle_quadruple!(4, 2, 2, 3, 3, zzww);
vector_swizzle_quadruple!(4, 2, 2, 3, 3, bbaa);
vector_swizzle_quadruple!(4, 2, 3, 0, 0, zwxx);
vector_swizzle_quadruple!(4, 2, 3, 0, 0, barr);
vector_swizzle_quadruple!(4, 2, 3, 0, 1, zwxy);
vector_swizzle_quadruple!(4, 2, 3, 0, 1, barg);
vector_swizzle_quadruple!(4, 2, 3, 0, 2, zwxz);
vector_swizzle_quadruple!(4, 2, 3, 0, 2, barb);
vector_swizzle_quadruple!(4, 2, 3, 0, 3, zwxw);
vector_swizzle_quadruple!(4, 2, 3, 0, 3, bara);
vector_swizzle_quadruple!(4, 2, 3, 1, 0, zwyx);
vector_swizzle_quadruple!(4, 2, 3, 1, 0, bagr);
vector_swizzle_quadruple!(4, 2, 3, 1, 1, zwyy);
vector_swizzle_quadruple!(4, 2, 3, 1, 1, bagg);
vector_swizzle_quadruple!(4, 2, 3, 1, 2, zwyz);
vector_swizzle_quadruple!(4, 2, 3, 1, 2, bagb);
vector_swizzle_quadruple!(4, 2, 3, 1, 3, zwyw);
vector_swizzle_quadruple!(4, 2, 3, 1, 3, baga);
vector_swizzle_quadruple!(4, 2, 3, 2, 0, zwzx);
vector_swizzle_quadruple!(4, 2, 3, 2, 0, babr);
vector_swizzle_quadruple!(4, 2, 3, 2, 1, zwzy);
vector_swizzle_quadruple!(4, 2, 3, 2, 1, babg);
vector_swizzle_quadruple!(4, 2, 3, 2, 2, zwzz);
vector_swizzle_quadruple!(4, 2, 3, 2, 2, babb);
vector_swizzle_quadruple!(4, 2, 3, 2, 3, zwzw);
vector_swizzle_quadruple!(4, 2, 3, 2, 3, baba);
vector_swizzle_quadruple!(4, 2, 3, 3, 0, zwwx);
vector_swizzle_quadruple!(4, 2, 3, 3, 0, baar);
vector_swizzle_quadruple!(4, 2, 3, 3, 1, zwwy);
vector_swizzle_quadruple!(4, 2, 3, 3, 1, baag);
vector_swizzle_quadruple!(4, 2, 3, 3, 2, zwwz);
vector_swizzle_quadruple!(4, 2, 3, 3, 2, baab);
vector_swizzle_quadruple!(4, 2, 3, 3, 3, zwww);
vector_swizzle_quadruple!(4, 2, 3, 3, 3, baaa);
vector_swizzle_quadruple!(4, 3, 0, 0, 0, wxxx);
vector_swizzle_quadruple!(4, 3, 0, 0, 0, arrr);
vector_swizzle_quadruple!(4, 3, 0, 0, 1, wxxy);
vector_swizzle_quadruple!(4, 3, 0, 0, 1, arrg);
vector_swizzle_quadruple!(4, 3, 0, 0, 2, wxxz);
vector_swizzle_quadruple!(4, 3, 0, 0, 2, arrb);
vector_swizzle_quadruple!(4, 3, 0, 0, 3, wxxw);
vector_swizzle_quadruple!(4, 3, 0, 0, 3, arra);
vector_swizzle_quadruple!(4, 3, 0, 1, 0, wxyx);
vector_swizzle_quadruple!(4, 3, 0, 1, 0, argr);
vector_swizzle_quadruple!(4, 3, 0, 1, 1, wxyy);
vector_swizzle_quadruple!(4, 3, 0, 1, 1, argg);
vector_swizzle_quadruple!(4, 3, 0, 1, 2, wxyz);
vector_swizzle_quadruple!(4, 3, 0, 1, 2, argb);
vector_swizzle_quadruple!(4, 3, 0, 1, 3, wxyw);
vector_swizzle_quadruple!(4, 3, 0, 1, 3, arga);
vector_swizzle_quadruple!(4, 3, 0, 2, 0, wxzx);
vector_swizzle_quadruple!(4, 3, 0, 2, 0, arbr);
vector_swizzle_quadruple!(4, 3, 0, 2, 1, wxzy);
vector_swizzle_quadruple!(4, 3, 0, 2, 1, arbg);
vector_swizzle_quadruple!(4, 3, 0, 2, 2, wxzz);
vector_swizzle_quadruple!(4, 3, 0, 2, 2, arbb);
vector_swizzle_quadruple!(4, 3, 0, 2, 3, wxzw);
vector_swizzle_quadruple!(4, 3, 0, 2, 3, arba);
vector_swizzle_quadruple!(4, 3, 0, 3, 0, wxwx);
vector_swizzle_quadruple!(4, 3, 0, 3, 0, arar);
vector_swizzle_quadruple!(4, 3, 0, 3, 1, wxwy);
vector_swizzle_quadruple!(4, 3, 0, 3, 1, arag);
vector_swizzle_quadruple!(4, 3, 0, 3, 2, wxwz);
vector_swizzle_quadruple!(4, 3, 0, 3, 2, arab);
vector_swizzle_quadruple!(4, 3, 0, 3, 3, wxww);
vector_swizzle_quadruple!(4, 3, 0, 3, 3, araa);
vector_swizzle_quadruple!(4, 3, 1, 0, 0, wyxx);
vector_swizzle_quadruple!(4, 3, 1, 0, 0, agrr);
vector_swizzle_quadruple!(4, 3, 1, 0, 1, wyxy);
vector_swizzle_quadruple!(4, 3, 1, 0, 1, agrg);
vector_swizzle_quadruple!(4, 3, 1, 0, 2, wyxz);
vector_swizzle_quadruple!(4, 3, 1, 0, 2, agrb);
vector_swizzle_quadruple!(4, 3, 1, 0, 3, wyxw);
vector_swizzle_quadruple!(4, 3, 1, 0, 3, agra);
vector_swizzle_quadruple!(4, 3, 1, 1, 0, wyyx);
vector_swizzle_quadruple!(4, 3, 1, 1, 0, aggr);
vector_swizzle_quadruple!(4, 3, 1, 1, 1, wyyy);
vector_swizzle_quadruple!(4, 3, 1, 1, 1, aggg);
vector_swizzle_quadruple!(4, 3, 1, 1, 2, wyyz);
vector_swizzle_quadruple!(4, 3, 1, 1, 2, aggb);
vector_swizzle_quadruple!(4, 3, 1, 1, 3, wyyw);
vector_swizzle_quadruple!(4, 3, 1, 1, 3, agga);
vector_swizzle_quadruple!(4, 3, 1, 2, 0, wyzx);
vector_swizzle_quadruple!(4, 3, 1, 2, 0, agbr);
vector_swizzle_quadruple!(4, 3, 1, 2, 1, wyzy);
vector_swizzle_quadruple!(4, 3, 1, 2, 1, agbg);
vector_swizzle_quadruple!(4, 3, 1, 2, 2, wyzz);
vector_swizzle_quadruple!(4, 3, 1, 2, 2, agbb);
vector_swizzle_quadruple!(4, 3, 1, 2, 3, wyzw);
vector_swizzle_quadruple!(4, 3, 1, 2, 3, agba);
vector_swizzle_quadruple!(4, 3, 1, 3, 0, wywx);
vector_swizzle_quadruple!(4, 3, 1, 3, 0, agar);
vector_swizzle_quadruple!(4, 3, 1, 3, 1, wywy);
vector_swizzle_quadruple!(4, 3, 1, 3, 1, agag);
vector_swizzle_quadruple!(4, 3, 1, 3, 2, wywz);
vector_swizzle_quadruple!(4, 3, 1, 3, 2, agab);
vector_swizzle_quadruple!(4, 3, 1, 3, 3, wyww);
vector_swizzle_quadruple!(4, 3, 1, 3, 3, agaa);
vector_swizzle_quadruple!(4, 3, 2, 0, 0, wzxx);
vector_swizzle_quadruple!(4, 3, 2, 0, 0, abrr);
vector_swizzle_quadruple!(4, 3, 2, 0, 1, wzxy);
vector_swizzle_quadruple!(4, 3, 2, 0, 1, abrg);
vector_swizzle_quadruple!(4, 3, 2, 0, 2, wzxz);
vector_swizzle_quadruple!(4, 3, 2, 0, 2, abrb);
vector_swizzle_quadruple!(4, 3, 2, 0, 3, wzxw);
vector_swizzle_quadruple!(4, 3, 2, 0, 3, abra);
vector_swizzle_quadruple!(4, 3, 2, 1, 0, wzyx);
vector_swizzle_quadruple!(4, 3, 2, 1, 0, abgr);
vector_swizzle_quadruple!(4, 3, 2, 1, 1, wzyy);
vector_swizzle_quadruple!(4, 3, 2, 1, 1, abgg);
vector_swizzle_quadruple!(4, 3, 2, 1, 2, wzyz);
vector_swizzle_quadruple!(4, 3, 2, 1, 2, abgb);
vector_swizzle_quadruple!(4, 3, 2, 1, 3, wzyw);
vector_swizzle_quadruple!(4, 3, 2, 1, 3, abga);
vector_swizzle_quadruple!(4, 3, 2, 2, 0, wzzx);
vector_swizzle_quadruple!(4, 3, 2, 2, 0, abbr);
vector_swizzle_quadruple!(4, 3, 2, 2, 1, wzzy);
vector_swizzle_quadruple!(4, 3, 2, 2, 1, abbg);
vector_swizzle_quadruple!(4, 3, 2, 2, 2, wzzz);
vector_swizzle_quadruple!(4, 3, 2, 2, 2, abbb);
vector_swizzle_quadruple!(4, 3, 2, 2, 3, wzzw);
vector_swizzle_quadruple!(4, 3, 2, 2, 3, abba);
vector_swizzle_quadruple!(4, 3, 2, 3, 0, wzwx);
vector_swizzle_quadruple!(4, 3, 2, 3, 0, abar);
vector_swizzle_quadruple!(4, 3, 2, 3, 1, wzwy);
vector_swizzle_quadruple!(4, 3, 2, 3, 1, abag);
vector_swizzle_quadruple!(4, 3, 2, 3, 2, wzwz);
vector_swizzle_quadruple!(4, 3, 2, 3, 2, abab);
vector_swizzle_quadruple!(4, 3, 2, 3, 3, wzww);
vector_swizzle_quadruple!(4, 3, 2, 3, 3, abaa);
vector_swizzle_quadruple!(4, 3, 3, 0, 0, wwxx);
vector_swizzle_quadruple!(4, 3, 3, 0, 0, aarr);
vector_swizzle_quadruple!(4, 3, 3, 0, 1, wwxy);
vector_swizzle_quadruple!(4, 3, 3, 0, 1, aarg);
vector_swizzle_quadruple!(4, 3, 3, 0, 2, wwxz);
vector_swizzle_quadruple!(4, 3, 3, 0, 2, aarb);
vector_swizzle_quadruple!(4, 3, 3, 0, 3, wwxw);
vector_swizzle_quadruple!(4, 3, 3, 0, 3, aara);
vector_swizzle_quadruple!(4, 3, 3, 1, 0, wwyx);
vector_swizzle_quadruple!(4, 3, 3, 1, 0, aagr);
vector_swizzle_quadruple!(4, 3, 3, 1, 1, wwyy);
vector_swizzle_quadruple!(4, 3, 3, 1, 1, aagg);
vector_swizzle_quadruple!(4, 3, 3, 1, 2, wwyz);
vector_swizzle_quadruple!(4, 3, 3, 1, 2, aagb);
vector_swizzle_quadruple!(4, 3, 3, 1, 3, wwyw);
vector_swizzle_quadruple!(4, 3, 3, 1, 3, aaga);
vector_swizzle_quadruple!(4, 3, 3, 2, 0, wwzx);
vector_swizzle_quadruple!(4, 3, 3, 2, 0, aabr);
vector_swizzle_quadruple!(4, 3, 3, 2, 1, wwzy);
vector_swizzle_quadruple!(4, 3, 3, 2, 1, aabg);
vector_swizzle_quadruple!(4, 3, 3, 2, 2, wwzz);
vector_swizzle_quadruple!(4, 3, 3, 2, 2, aabb);
vector_swizzle_quadruple!(4, 3, 3, 2, 3, wwzw);
vector_swizzle_quadruple!(4, 3, 3, 2, 3, aaba);
vector_swizzle_quadruple!(4, 3, 3, 3, 0, wwwx);
vector_swizzle_quadruple!(4, 3, 3, 3, 0, aaar);
vector_swizzle_quadruple!(4, 3, 3, 3, 1, wwwy);
vector_swizzle_quadruple!(4, 3, 3, 3, 1, aaag);
vector_swizzle_quadruple!(4, 3, 3, 3, 2, wwwz);
vector_swizzle_quadruple!(4, 3, 3, 3, 2, aaab);
vector_swizzle_quadruple!(4, 3, 3, 3, 3, wwww);
vector_swizzle_quadruple!(4, 3, 3, 3, 3, aaaa);
// ---------------------

